mbta/arrow

assets/package.json, assets/tsconfig.json, codecov.yml, config/test.exs, mix.exs, semaphore/credo.sh, semaphore/dialyzer.sh, semaphore/format.sh, semaphore/setup.sh, semaphore/test.sh
- elixir: mix format, test, credo, dialyzer
- typescript: npm test and npm run check
- install versions of erlang, elixir, node matching `.tool-versions`
- also install latest npm along with the new node version; the preinstalled one doesn't have `npm ci`
=> feat: basic CI setup

lib/arrow_web/controllers/health_controller.ex, lib/arrow_web/router.ex, test/arrow_web/controllers/health_controller_test.exs
Ticket: [🏹 Add /_health URL](https://app.asana.com/0/584764604969369/1154773501302865/f)
=> feat: add /_health endpoint

config/config.exs, config/dev.exs, config/prod.exs, config/test.exs, lib/arrow/ueberauth/strategy/fake.ex, lib/arrow_web/auth_manager.ex, lib/arrow_web/auth_manager/error_handler.ex, lib/arrow_web/auth_manager/pipeline.ex, lib/arrow_web/controllers/auth_controller.ex, lib/arrow_web/controllers/unauthorized_controller.ex, lib/arrow_web/ensure_arrow_group.ex, lib/arrow_web/router.ex, lib/arrow_web/templates/unauthorized/index.html.eex, lib/arrow_web/views/unauthorized_view.ex, mix.exs, mix.lock, test/arrow/ueberauth/strategy/fake_test.exs, test/arrow_web/auth_manager/error_handler_test.exs, test/arrow_web/auth_manager_test.exs, test/arrow_web/controllers/auth_controller_test.exs, test/arrow_web/controllers/page_controller_test.exs, test/arrow_web/controllers/unauthorized_controller_test.exs, test/arrow_web/ensure_arrow_group_test.exs, test/support/conn_case.ex
Ticket: [AWS Cognito integration](https://app.asana.com/0/584764604969369/1145845426232983/f)
Should be reviewable commit-by-commit in a clean way. A lot of this is carried over fairly directly from Signs UI, so it may be instructive to look there as well.
=> feat: AWS Cognito integration

codecov.yml
=> feat: require 100% coverage of patches

codecov.yml
💯 but for real this time, hopefully.
=> fix: shouldn't have "true" after "patch:" in codecov.yml

lib/arrow/disruption.ex, lib/arrow/disruption/exception.ex, lib/arrow/disruption/trip_short_name.ex, priv/repo/migrations/20191223181711_create_disruption_exceptions.exs, priv/repo/migrations/20191223181837_create_disruption_trip_short_names.exs, test/arrow/disruption_test.exs
These are easier than the recurrences, so starting with them.
=> feat(Disruption): date exceptions and trip short names

config/config.exs, config/test.exs, lib/arrow/application.ex, lib/arrow_web/controllers/api/adjustment_controller.ex, lib/arrow_web/router.ex, test/arrow_web/controllers/api/adjustment_controller_test.exs
Asana ticket: [🏹 JSON API to list all adjustments](https://app.asana.com/0/584764604969369/1157557244099563/f)
Changes:
* Added `ArrowWeb.API.AdjustmentController`
* filter by `route_id`
* filter by `source`
* Updated `Arrow.Application` to not read in adjustments on startup when testing
=> feat: Adjustment list api

mix.lock
Updating Jason in #108 interacted poorly with other changes in #113.
=> chore: mix deps.unlock to fix issue with jason

test/arrow_web/controllers/api/adjustment_controller_test.exs, test/arrow_web/controllers/api/disruption_controller_test.exs
**Asana Ticket:** none
These two tests are failing on master. Separately, we should figure out why semaphore wasn't failing.
=> fix: Fix failing tests

assets/package-lock.json, assets/package.json, assets/src/disruptions/disruptions.ts, assets/src/disruptions/newDisruption.tsx, assets/src/disruptions/viewDisruption.tsx, assets/src/header.tsx, assets/src/jsonApi.ts, assets/src/loading.tsx, assets/tests/disruptions/newDisruption.test.tsx, assets/tests/jsonApi.test.ts
**Asana Ticket:** [🏹 List of adjustments flows through to new/edit pages](https://app.asana.com/0/584764604969369/1157557244099561/f)
The two commits should be reviewable independently.
=> Adjustments flow to front end

assets/webpack.config.js
=> fix: New CopyWebpackPlugin has a new config format

lib/arrow/disruption.ex, lib/arrow/disruption/day_of_week.ex, lib/arrow_web/controllers/api/disruption_controller.ex, lib/arrow_web/utilities.ex, test/arrow/disruption_test.exs, test/arrow_web/controllers/api/disruption_controller_test.exs, test/arrow_web/utilities_test.exs, test/support/data_case.ex
**Asana Ticket:** [🏹 Arrow has validation for disruptions](https://app.asana.com/0/584764604969369/1173526948047133/f)
Validations added:
* start date shouldn't be after end date
* days of week should fall between start and end date
* any exception dates should fall between start and end date
* exception dates should be unique, and should be applicable to days of week 
* start time happens before end time
=> feat: disruption validations

assets/package-lock.json, assets/package.json
**Asana Ticket:** [tend to dependabot ](https://app.asana.com/0/584764604969369/1180111884960465/f)
I've tested this out locally and everything seems to be working fine.
=> chore: bump front-end dependencies

priv/repo/migrations/20200713155611_create_auth_tokens.exs, priv/repo/structure.sql
**Asana Ticket:** [🏹 figure out authentication for existing arrow API](https://app.asana.com/0/584764604969369/1173297500981963/f)
Putting the migration in a separate PR so we can deploy it first, _then_ the code that actually uses the table.
=> chore: migration to create auth_tokens table

lib/arrow/auth_token.ex, lib/arrow_web/controllers/auth_controller.ex, lib/arrow_web/controllers/my_token_controller.ex, lib/arrow_web/router.ex, lib/arrow_web/templates/my_token/index.html.eex, lib/arrow_web/try_api_token_auth.ex, lib/arrow_web/views/my_token_view.ex, test/arrow/auth_token_test.exs, test/arrow_web/controllers/api/disruption_controller_test.exs, test/arrow_web/controllers/auth_controller_test.exs, test/arrow_web/controllers/my_token_controller_test.exs, test/arrow_web/try_api_token_auth_test.exs, test/support/conn_case.ex
**Asana Ticket:** [🏹 figure out authentication for existing arrow API](https://app.asana.com/0/584764604969369/1173297500981963/f)
Should be reviewable commit-by-commit.
=> Allow API authentication via token

assets/package-lock.json, assets/package.json, assets/src/disruptions/newDisruption.tsx, assets/src/models/adjustment.ts, assets/tests/disruptions/disruptionCalendar.test.tsx, assets/tests/disruptions/disruptionIndex.test.tsx, assets/tests/disruptions/disruptionSummary.test.tsx, assets/tests/disruptions/disruptionTable.test.tsx, assets/tests/disruptions/newDisruption.test.tsx, assets/tests/models/disruption.test.ts
**Asana Ticket:** [🏹 Combo-box for adjustment selection](https://app.asana.com/0/584764604969369/1157557244099569/f)
Changes:
* replace current `AdjustmentPicker` with new version using `react-select`
* change frontend `Adjustment` model to make `id`, `routeId` and `sourceLabel` required
* updated tests as needed
=> feat: add react-select for adjustment picker

.tool-versions, Dockerfile
**Asana Ticket:** [[extra] Upgrade nodejs in Arrow](https://app.asana.com/0/584764604969369/1189503821005857/f)
The code was actually initially written by @losvedir, I'm just helpfully carving it off into a separate branch. 🙂
=> chore: Upgrade to NodeJS 14.x

priv/repo/migrations/20200812222513_draft_disruptions.exs
Fix migration issue. Since the current migration file fails, the previous attempt was rolled back, so the file can still be edited.
=> fix: migration to new schema

assets/src/disruptions/disruptionIndex.tsx, assets/tests/disruptions/disruptionIndex.test.tsx
**Asana Ticket:** [🏹 User can toggle between draft and published views on homepage](https://app.asana.com/0/584764604969369/1186492610975117/f)
Used `useDisruptionViewParam` hook and `DisruptionViewToggle` component introduced in https://github.com/mbta/arrow/pull/400 to conditionally fetch draft or published Disruptions on the index page
=> feat: add ability to toggle between published and draft views on home page

assets/src/disruptions/disruptionIndex.tsx, assets/src/disruptions/viewDisruption.tsx, assets/src/disruptions/viewToggle.tsx, assets/tests/disruptions/disruptionCalendar.test.tsx, assets/tests/disruptions/disruptionIndex.test.tsx, assets/tests/disruptions/disruptionTable.test.tsx, assets/tests/disruptions/viewDisruption.test.tsx, lib/arrow/disruption.ex, lib/arrow/disruption_revision.ex, lib/arrow_web/controllers/api/disruption_controller.ex, lib/arrow_web/controllers/api/disruption_diff_controller.ex, lib/arrow_web/controllers/temp_review_changes_controller.ex, lib/mix/tasks/copy_db.ex, priv/repo/migrations/20200909124316_add_ready_revision_id.exs, test/arrow/disruption_revision_test.exs, test/arrow/disruption_test.exs, test/arrow_web/controllers/api/disruption_controller_test.exs, test/arrow_web/controllers/api/disruption_diff_controller_test.exs, test/arrow_web/controllers/temp_review_changes_controller_test.exs, test/mix/tasks/copy_db_test.exs, test/support/factory.ex
**Asana Ticket:** [🏹 Data model updates](https://app.asana.com/0/584764604969369/1191956107867590/f)
Per earlier discussion, I'm going to include the migration in the same PR since it should be very fast.
=> ready_revision data model

assets/src/disruptions/disruptionCalendar.tsx, assets/src/disruptions/disruptionIndex.tsx, assets/src/disruptions/disruptionNeedsReview.tsx, assets/src/disruptions/disruptionTable.tsx, assets/src/disruptions/editDisruption.tsx, assets/src/disruptions/newDisruption.tsx, assets/src/disruptions/viewDisruption.tsx, assets/src/disruptions/viewToggle.tsx, assets/src/jsonApi.ts, assets/src/models/disruption.ts, assets/src/models/disruptionDiff.ts, assets/src/models/disruptionRevision.ts, assets/tests/disruptions/disruptionCalendar.test.tsx, assets/tests/disruptions/disruptionIndex.test.tsx, assets/tests/disruptions/disruptionTable.test.tsx, assets/tests/disruptions/editDisruption.test.tsx, assets/tests/disruptions/viewDisruption.test.tsx, assets/tests/disruptions/viewToggle.test.ts, assets/tests/jsonApi.test.ts, assets/tests/models/disruption.test.ts, assets/tests/models/disruptionRevision.test.ts, lib/arrow/disruption.ex, lib/arrow_web/controllers/api/disruption_controller.ex, lib/arrow_web/views/api/disruption_diff_view.ex, lib/arrow_web/views/api/disruption_revision_view.ex, lib/arrow_web/views/api/disruption_view.ex, test/arrow/disruption_revision_test.exs, test/arrow_web/controllers/api/disruption_controller_test.exs
**Asana Ticket:** [🏹 Frontend serialization updates](https://app.asana.com/0/584764604969369/1191956107867592/f)
Will need to coordinate merging and deploying with @losvedir's upcoming gtfs_creator PR.
=> 🏹 Frontend serialization updates

lib/arrow/disruption/published_after_ready_error.ex, lib/arrow/disruption_revision.ex, lib/arrow_web/controllers/api/publish_notice_controller.ex, lib/arrow_web/router.ex, test/arrow/disruption_revision_test.exs, test/arrow_web/controllers/api/publish_notice_controller_test.exs
**Asana Ticket:** [🏹 Create Arrow API endpoint for gtfs_creator: "published_revision_id"](https://app.asana.com/0/584764604969369/1191956107867614/f)
New API endpoint on the Arrow side, gtfs_creator side changes coming shortly.
=> feat: publish_notice API endpoint

priv/repo/migrations/20200925153736_disruptions_last_published_at.exs, priv/repo/structure.sql
**Asana Ticket:** Related to: [Track publish date and flow dates to frontend](https://app.asana.com/0/584764604969369/1195117716558248)
Just the DB side of things. I also noticed that our `structure.sql` was a bit out of date, so I updated it in a first commit, so that you can more clearly see just the changes from this migration in the second commit.
=> Update DB schema: last_published at

assets/src/models/disruption.ts, assets/src/models/disruptionRevision.ts, assets/tests/models/disruption.test.ts, assets/tests/models/disruptionRevision.test.ts, lib/arrow/disruption.ex, lib/arrow/disruption_revision.ex, lib/arrow_web/views/api/disruption_revision_view.ex, lib/arrow_web/views/api/disruption_view.ex, test/arrow/disruption_revision_test.exs
**Asana Ticket:** [🏹 Track publish date and flow dates to frontend](https://outlook.office365.com/mail/inbox/id/AAQkADYxNzhkNWFhLTgzZDktNDQ1My1iNzcwLTY2ZmFhY2YyYmM1YgAQAPs59zbWkcxDoKjbcPNJxB4%3D)
=> feat: Track last_published_at and other dates on frontend

lib/arrow/db_structure.ex, lib/arrow_web/controllers/api/db_dump_controller.ex, lib/arrow_web/router.ex, lib/mix/tasks/copy_db.ex, test/arrow/db_structure_test.exs, test/arrow_web/controllers/api/db_dump_controller_test.exs, test/mix/tasks/copy_db_test.exs
**Asana Ticket:** [🏹 Update copy_db mix task to use a DB dump endpoint](https://app.asana.com/0/584764604969369/1191956107867618/f)
Okay, whew, I think I finally got everything working. The commits should be fairly easy to review individually.
=> Improve copy_db Mix task with API endpoint

assets/src/disruptions/disruptionIndex.tsx, assets/tests/disruptions/disruptionIndex.test.tsx
**Asana Ticket:** [🏹 Add ability to filter disruptions by date](https://app.asana.com/0/584764604969369/1196891093454891)
By default the table view now excludes disruptions that ended more than 7 days ago (relative to when the view was loaded). A new "include past" filter button brings the old disruptions back.
=> feat: add filter for past disruptions

semaphore/build_push.sh
=> chore: login to Docker Hub in CI

lib/arrow/disruption_revision.ex, test/arrow/disruption_revision_test.exs
`gtfs_creator` always sends the revision IDs of all disruptions it is publishing; Arrow in turn would always update the "published" timestamp on all the corresponding disruptions, even if their published revisions didn't change. This made the timestamp not that useful, since it would always just be the timestamp of the last GTFS deploy for all (published) disruptions.
This changes the logic to only update the "published" timestamp when the published revision changes.
**Asana Ticket:** [🐛 arrow "published" keeping last publish date without new info](https://app.asana.com/0/584764604969369/1199519213885301)
=> fix: only bump published date if revision changes

semaphore/test.sh
**Asana Ticket:** [disable CodeCov on arrow](https://app.asana.com/0/584764604969369/1200274986747479)
Made another ticket for switching CI to GitHub actions (including code coverage), once we figure out the DB side of things. For now, this just removes CodeCov in advance of closing our account this week.
=> chore: Remove CodeCov

assets/css/app.css, assets/css/footer.css, lib/arrow_web/templates/layout/app.html.eex
**Asana Ticket:** [🏹 giving arrow a footer](https://app.asana.com/0/584764604969369/1200768039759886)
Layout based on: https://getbootstrap.com/docs/4.6/examples/sticky-footer/
=> feat: add footer with contact information

.github/workflows/asana.yml
**Asana Ticket:** https://app.asana.com/0/584764604969369/1206559294229662
Updated the asana integration to use our shared workflow
=> Update asana integation to use shared workflow

test/integration/disruptions_test.exs
tests: add test for updating a disruption
=> tests: add test for updating a disruption

lib/mix/tasks/copy_db.ex, mix.exs
Potential resolution to credo complaint in https://github.com/mbta/arrow/pull/971
=> fix: address credo complaint

.credo.exs, .github/workflows/ci.yml, lib/arrow/shuttle.ex, lib/arrow/shuttle/shape.ex, lib/arrow/shuttle/shape_upload.ex, lib/arrow/shuttle/shapes_upload.ex, lib/arrow_web/controllers/shape_controller.ex, lib/arrow_web/controllers/shape_html/new_bulk.html.heex, lib/arrow_web/controllers/shape_html/select.html.heex, lib/arrow_web/controllers/shape_html/show.html.heex, priv/repo/migrations/20240628203237_remove_coordinates_from_shape.exs, priv/repo/structure.sql, test/arrow_web/controllers/shape_controller_test.exs
**Asana Ticket:** [🏹  Implement Shuttle Route KML Upload and Shape Selection](https://app.asana.com/0/home/1205718273834955/1207339672568992)
=> feat: add shape selection and naming

config/config.exs, config/dev.exs, config/prod.exs, lib/arrow/shuttle.ex, lib/arrow/shuttle/kml.ex, lib/arrow/shuttle/shape_kml.ex, lib/arrow/shuttle/shape_upload.ex, lib/arrow/shuttle/shapes_upload.ex, lib/arrow_web/controllers/layout_html/_flash.html.heex, lib/arrow_web/controllers/shape_controller.ex, lib/arrow_web/controllers/shape_html/select.html.heex, lib/arrow_web/router.ex, test/arrow/shuttle_test.exs, test/arrow_web/controllers/shape_controller_test.exs
**Asana Ticket:** [🏹 Add upload of KML file per processed shape](https://app.asana.com/0/584764604969369/1207791571342366/f)
=> Add upload of a kml file per processed shape

lib/arrow/shuttle/shapes_upload.ex, lib/arrow_web/components/core_components.ex, lib/arrow_web/controllers/shape_html/new_bulk.html.heex, lib/arrow_web/controllers/shape_html/select.html.heex, lib/arrow_web/controllers/shape_html/show.html.heex, test/arrow_web/controllers/shape_controller_test.exs
**Asana Ticket:** [ 🏹  Polish Shuttle Route KML Upload and Shape Selection](https://app.asana.com/0/1205718273834959/1207791577677461/f)
=> feat: deduplicate consecutive coordinates in shapes, UI polish

lib/arrow_web/controllers/stop_html.ex, lib/arrow_web/controllers/stop_html/index.html.heex, test/arrow_web/controllers/stop_html_test.exs
**Asana Ticket:** [🏹 Implement "View Shuttle Stops" Page](https://app.asana.com/0/584764604969369/1207472819136794/f)
* Added last updated column
=> feat: add last updated column to stops list

Dockerfile
**Asana Ticket:** NO TICKET
Based on [this thread](https://mbta.slack.com/archives/G01E809HUF2/p1724269617376789), it looks like this update is expected
=> fix: update bundle hash

.envrc.example, README.md, config/dev.exs, lib/arrow/shuttle.ex, lib/arrow/shuttle/shape.ex, lib/arrow/shuttle/shape_upload.ex, test/arrow/shuttle/shape_test.exs, test/arrow/shuttle_test.exs, test/arrow_web/controllers/shape_controller_test.exs, test/support/fixtures/shuttle_fixtures.ex
**Asana Ticket:** [🏹 Append -S in Arrow shape save](https://app.asana.com/0/1204473309455397/1208045514739578/f)
=> 🏹 Append -S in Arrow shape save

.github/workflows/ci.yml, lib/arrow_web/endpoint.ex
**Asana Ticket:** [🚝 Upload new gtfs-creator builds to Arrow upon deploy](https://app.asana.com/0/584764604969369/1207956859977578/f)
=> fix: increase length to 100MB for multipart uploads in Plug.Parsers

lib/arrow_web/live/stop_live/stop_view_live.html.heex
**Asana Ticket:** [[extra] 🏹 Adjust layout of Create + Edit Stop pages](https://app.asana.com/0/584764604969369/1208623002791926/f)
See also some discussion of the specifics [in Slack](https://mbta.slack.com/archives/C07639BHFKR/p1729771458455419)
=> feat: place form and map side by side on shuttle stop page

Dockerfile
Failing deploy to dev from main branch: https://github.com/mbta/arrow/actions/runs/11810931841/job/32903713444
https://github.com/mbta/arrow/pull/1009
`curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem | shasum -a 256`
=> chore: update aws cert bundle

priv/repo/migrations/20241210155455_update_developer_token.exs
**Asana Ticket:** [[extra] Arrow token issue with GTFS deploy](https://app.asana.com/0/584764604969369/1208939937983434/f)
See [Slack discussion](https://mbta.slack.com/archives/C07639BHFKR/p1733779726893599).
=> chore: update developer API token username to match Keycloak format

.github/workflows/ci.yml, priv/repo/migrations/20241209204043_add_new_route_desc_values.exs, priv/repo/structure.sql
**Asana Ticket:** ad hoc
(Related to [❄️🚝 Adopt new `route_desc` nomenclature](https://app.asana.com/0/584764604969369/1208568277176437/f) though)
```
$ mix ecto.migrate
[info] == Running 20241209204043 Arrow.Repo.Migrations.AddNewRouteDescValues.up/0 forward
[info] execute "ALTER TYPE route_desc ADD VALUE 'Regional Rail'"
[info] execute "ALTER TYPE route_desc ADD VALUE 'Coverage Bus'"
[info] execute "ALTER TYPE route_desc ADD VALUE 'Frequent Bus'"
[info] == Migrated 20241209204043 in 0.0s
```
```
$ mix ecto.rollback -n 1
[info] == Running 20241209204043 Arrow.Repo.Migrations.AddNewRouteDescValues.down/0 forward
[debug] QUERY OK source="gtfs_routes" db=1.5ms
UPDATE "gtfs_routes" AS g0 SET "desc" = $1 WHERE (g0."desc" = $2) ["Commuter Rail", "Regional Rail"]
[debug] QUERY OK …
```
=> chore: Update `route_desc` DB enum type

assets/src/components/BaseMapLayerControl.tsx, assets/src/components/ShapeViewMap.tsx, assets/src/components/StopViewMap.tsx
**Asana Ticket:** [🏹 Implement MassGIS Aerial Imagery Tileset + Base Map Selection](https://app.asana.com/0/1208877354377530/1208652433539046)
=> feat(shapes): add toggle for base map layer (satellite vs street map)

assets/src/app.tsx, assets/src/components/ShapeStopViewMap.tsx, lib/arrow_web/live/shuttle_live/shuttle_live.ex
**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" Map View - Stop Display](https://app.asana.com/0/1204473309455397/1208573748126858/f)
=> 🏹 Implement "Create/Edit Shuttle Route Definition" Map View - Stop Display

priv/repo/structure.sql
**Asana Ticket:** no ticket, just a one-off
It looks like while doing #1050 I neglected to actually commit the relevant change to `structure.sql` to add the record of the migration. Right now doing anything that runs the migrations locally creates a new unrelated diff in `structure.sql` to reflect the change, so this PR just adds it for real.
=> chore: update structure.sql

lib/arrow_web/live/shuttle_live/shuttle_live.ex
* Update function names for shape live-select formatting functions
=> refactor(shuttle): rename shape live-select functions

lib/arrow_web/live/stop_live/stop_live.ex
**Asana Ticket:** N/A
Fixes splunk crash here: https://mbtace.sentry.io/issues/6181003717/?environment=dev&project=4504753753751552&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=1
We were trying to turn an empty string to an integer, which throws. Let's fix that
=> fix(stops): fix stop view crash when creating new stop

assets/src/components/ShapeStopViewMap.tsx
**Asana Ticket:** [[extra] 🏹 Skate tileset for shuttle route definition pages](https://app.asana.com/0/584764604969369/1209094056922522/f)
=> fix: also use layers selector on shuttle definition page

lib/arrow_web/auth_manager/error_handler.ex, lib/arrow_web/controllers/auth_controller.ex, test/arrow_web/auth_manager/error_handler_test.exs, test/arrow_web/controllers/auth_controller_test.exs
**Asana Ticket:** [[🏹] Take user to original destination after login](https://app.asana.com/0/1204473309455397/1209070894196125/f)
=> feat: redirect to original url after login

lib/arrow/disruptions.ex, lib/arrow/disruptions/disruption_v2.ex, lib/arrow/disruptions/replacement_service.ex, priv/repo/migrations/20250122204118_create_replacement_services.exs, priv/repo/structure.sql, test/arrow/disruptions_test.exs, test/support/fixtures/disruptions_fixtures.ex
**Asana Ticket:** Part of [🏹 Implement "Create Replacement Service Component" - Shuttle Activation Upload/Parsing + Save Component Button](https://app.asana.com/0/584764604969369/1208991517812079)
Adds the database schema and related modules for ReplacementService
I may wait to merge this until the form is complete but opening this up for  👀 anyway
=> feat: add replacement_service schema

lib/arrow/disruptions.ex, lib/arrow_web/controllers/api/limit_controller.ex, lib/arrow_web/controllers/api_html/limit_view.ex, lib/arrow_web/router.ex, test/arrow_web/controllers/api/limit_controller_test.exs, test/support/factory.ex
**Asana Ticket:** [🏹 Implement /limits API endpoint](https://app.asana.com/0/1204473309455397/1209072824896312/f)
=> 🏹 Implement /limits API endpoint

lib/arrow/disruptions.ex, lib/arrow/shuttles.ex, lib/arrow/shuttles/route.ex, lib/arrow/shuttles/route_stop.ex, lib/arrow_web/components/replacement_service_section.ex, lib/arrow_web/components/stop_input.ex, lib/arrow_web/controllers/timetable_controller.ex, lib/arrow_web/controllers/timetable_html.ex, lib/arrow_web/controllers/timetable_html/show.html.heex, lib/arrow_web/router.ex, test/arrow/disruptions_test.exs, test/arrow/shuttles_test.exs, test/arrow_web/controllers/api/replacement_service_controller_test.exs, test/arrow_web/controllers/timetable_controller_test.exs, test/support/factory.ex
**Asana Ticket:** [🏹 Implement Shuttle Activation Timetable View](https://app.asana.com/0/584764604969369/1208992890474694)
I opted to make this page a conventional controller as opposed to a LiveView as there is very little interactivity aside from a couple of links.
=> Parsed timetable view

lib/arrow_web/controllers/disruption_v2_html/_table.html.heex
The original table task didn't mention adding navigation to the edit button, but I should have added it. Super quick change to allow editing a disruption from the row in the table.
=> Add navigation to edit button.

lib/arrow_web/controllers/disruption_v2_controller/filters.ex, lib/arrow_web/controllers/disruption_v2_controller/index.ex, lib/arrow_web/controllers/disruption_v2_html/index.html.heex, test/arrow_web/controllers/disruption_v2_controller/filters_test.exs, test/arrow_web/controllers/disruption_v2_controller_test.exs
**Asana Ticket:** [🏹 Implement search box](https://app.asana.com/0/1204473309455397/1209170968037053)
=> 🏹 Implement search box

lib/arrow_web/components/limit_section.ex
**Asana Ticket:** [[extra] 🏹 Sort stops within dropdown lists in canonical order](https://app.asana.com/0/584764604969369/1209744130843620/f)
The stops in the dropdown were in no particular order which was frustrating for some folks. Fixed it so they are in `direction_id=0` canonical order instead.
=> tweak: Sort stop dropdowns

lib/arrow_web/components/limit_section.ex, lib/arrow_web/components/replacement_service_section.ex
The limits table deviated a bit from the mock-up, so tweaked the styles so it falls in line with other tables on the page.
=> polish: Limits table styling

lib/arrow/disruptions.ex, lib/arrow/hastus/export.ex, lib/arrow/hastus/export_upload.ex, lib/arrow/hastus/service.ex, lib/arrow_web/components/hastus_export_section.ex, priv/repo/migrations/20250320151207_update_hastus_foreign_key_columns.exs, priv/repo/structure.sql, test/integration/disruptionsv2/hastus_export_section_test.exs, test/support/fixtures/hastus_fixtures.ex
**Asana Ticket:** [🏹 Implement HASTUS Service Schedules Section](https://app.asana.com/0/584764604969369/1209459244072056/f)
This PRs adds a table to each disruption showing previously imported HASTUS exports. Users are able to edit/delete these exports using buttons on the corresponding row.
=> feat: HASTUS export table view

lib/arrow_web/live/shuttle_live/shuttle_live.ex
**Asana Ticket:** [🏹🐛 [extra] Fix save + cancel button in new shuttle definition page](https://app.asana.com/0/584764604969369/1209094056922516/f)
I borrowed the layout / styling from the Disruptions page so it should match that.
I have an outstanding question about consistent casing in the Arrow UI, but in the meantime I'm leaving the buttons Title Case which seems at least largely consistent within the shuttle page itself.
=> Fix shuttle page save button and add cancel button

lib/arrow/disruptions/replacement_service.ex, test/arrow/disruptions/replacement_service_test.exs
**Asana Ticket:** [🏹🐛  /api/replacement-service is returning pending disruptions](https://app.asana.com/0/1204137169527258/1209883873493219/f)
=> feat: don't return replacement_services for pending disrutpions

lib/arrow_web/controllers/layout_html/_footer.html.heex
Fix the department name in the footer.
=> fix: Department name in footer

lib/arrow_web/controllers/api/service_schedule_controller.ex
=> fix: include inferred route_id in trip_route_directions

lib/arrow/disruptions.ex, lib/arrow/hastus.ex, lib/arrow/hastus/export_upload.ex, lib/arrow/hastus/service.ex, lib/arrow_web/components/core_components.ex, lib/arrow_web/components/hastus_export_section.ex, lib/arrow_web/components/limit_section.ex, priv/repo/migrations/20250410180228_remove_hastus_service_start_end_stop_columns.exs, priv/repo/structure.sql, test/arrow/hastus/export_upload_test.exs, test/arrow/hastus_test.exs, test/integration/disruptionsv2/hastus_export_section_test.exs
Pulling this out since it isn't 100% right for all lines. The solution would cause parsing to timeout so we will need to consider moving the logic to a background process before adding back.
=> revert: HASTUS limit derivations

lib/arrow_web/components/limit_section.ex
- groups limits by their route, start, and end stops
- updates the limits section to use a grid layout for consistent column placement even with some rows not having all columns (route, start, end)
- includes days of week in the limits section
- falls back to a simple flexbox based layout at small breakpoints to prevent the element from overflowing its container
https://github.com/user-attachments/assets/0e3d9041-f73d-42ff-97ec-4444e4836ec7
[🏹💅🏻🇵🇱  Group Limits in Create/Edit Disruption Pages][asana]
[asana]: https://app.asana.com/1/15492006741476/project/584764604969369/task/1209887002402273?focus=true
=> feat: group limits by origin and destination

lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.html.heex
**Asana Ticket:** [Add navigation to create/edit disruption pages](https://app.asana.com/1/15492006741476/project/584764604969369/task/1209562587669644?focus=true)
Adds the navbar to the top of the disruption page / form.
Review ignoring whitespace for a clearer diff: https://github.com/mbta/arrow/pull/1227/files?diff=unified&w=1
=> feat: add navigation to disruption page

lib/arrow/disruptions/limit.ex, lib/arrow/disruptions/replacement_service.ex
**Asana Ticket:** [🏹🐛 Shuttles cannot be activated for a single day](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210014559418761?focus=true)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210005580087750
=> fix: allow single day limits and replacement service

lib/arrow_web/live/stop_live/stop_live.ex
**Asana Ticket:** [🏹💅🏻🇵🇱 [Create/Edit Stop Pages] Stop conventions link opens in new tab](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210003061542232?focus=true)
Open link in new tab.
=> polish: open View Shuttle Stop Conventions link in new tab

assets/src/components/ShapeStopViewMap.tsx, assets/src/components/stops/StopLayerControl.tsx
Updates labels of stops in map views to include their stop ids
**Asana Ticket:** [[Map Views] Show stop_ID on stop labels](https://app.asana.com/1/15492006741476/project/584764604969369/task/1209883863923163?focus=true)
<details>
<summary>🖼️ screenshots</summary>
https://github.com/user-attachments/assets/75acbd72-9257-4d60-aa9a-d6e8ee4c2610
</details>
=> feat: show stop_ids on stop labels in all map views

.github/workflows/ci.yml
**Asana Ticket:** [🏹 Use consistent Postgres version in CI & deployment envs](https://app.asana.com/1/15492006741476/project/584764604969369/task/1208939127624540?focus=true)
=> chore: update CI to use Postgres 15, consistent with prod
