mbta/arrow

config/config.exs
config/dev.exs
lib/arrow_web/router.ex
test/arrow_web/controllers/page_controller_test.exs
test/support/conn_case.ex

Ticket: [🏹 Redirect prod requests to HTTPS](https://app.asana.com/0/584764604969369/1154773501302867/f)
This is basically the same way Signs UI does it, but I went with the default-to-secure approach here and explicitly overrode it to _not_ redirect to HTTPs in dev and test. Apparently Codecov thinks this is fine and the equivalent code in Signs UI has no tests I can find, but it would be nice to test it somehow, I'm just not sure how...

feat: redirect http to https

---

config/config.exs
config/prod.exs
lib/arrow/application.ex
lib/arrow/repo/migrator.ex
test/arrow/application_test.exs
test/arrow/repo/migrator_test.exs

We run a transient GenServer to handle the migrations, and then stop when the
migrations complete. If there's an error, the supervision tree will restart
the migration task.

feat: run migrations at startup (prod only)

---

lib/arrow/adjustment.ex
lib/arrow/adjustment_fetcher.ex
lib/arrow/application.ex
priv/repo/migrations/20200129212636_update_adjustments_unique_index.exs
priv/repo/seeds.exs
test/arrow/adjustment_fetcher_test.exs
test/arrow/adjustment_test.exs
test/arrow/disruption_test.exs

Asana ticket: [🏹 Arrow loads adjustments on startup](https://app.asana.com/0/584764604969369/1157557244099559/f)
Two commits should be reviewable independently. The fact that the app now loads stuff into the database on startup makes testing a little weird. I've tried to make it all make sense, but some things like testing that the database starts out with no adjustments just don't really apply anymore.

Load adjustments on startup

---

assets/css/_forms.scss
assets/src/disruptions/disruptionTimePicker.tsx

Asana: [🏹 Days of week should be stylized circles rather than checkboxes](https://app.asana.com/0/584764604969369/1158326786257803).

feat: Style disruption 'day of week' selector

---

assets/src/disruptions/disruptionTimePicker.tsx
assets/src/disruptions/newDisruptionPreview.tsx
assets/tests/disruptions/disruptionTimePicker.test.tsx
assets/tests/disruptions/newDisruptionPreview.test.tsx

Asana ticket: [🏹 Time of day selectors should have AM/PM widget](https://app.asana.com/0/584764604969369/1158326786257805/f)

feat: disruption time of day picker

---

assets/css/_disruption_summary.scss
assets/src/disruptions/disruptionPreview.tsx
assets/src/disruptions/disruptionSummary.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/newDisruption.tsx
assets/tests/disruptions/disruptionPreview.test.tsx
assets/tests/disruptions/disruptionSummary.test.tsx
assets/tests/disruptions/editDisruption.test.tsx
assets/tests/disruptions/newDisruption.test.tsx

This should be all of the front-end logic that's feasible to do for now without having the API to actually save changes.
Right now I just have the "cancel" button redirecting to the view page URL for the corresponding disruption, but we might want to change that in the future if there are multiple ways that the user can reach the edit page.
Also note that I've included some dummy data just so that we can actually see the functionality of the edit page. We should remove this as soon as we have an API we can read from.

feat: front-end edit page

---

lib/arrow/disruption/day_of_week.ex
lib/arrow_web/views/api/day_of_week_view.ex
priv/repo/migrations/20200326133115_change_day_of_week_to_enum.exs
priv/repo/structure.sql
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs

The first commit just adds the output of `mix ecto.dump` to the repo. At my last company we had the generated schema checked in, and I found it to be a useful resource when developing, and also seeing what new migrations actually _do_, as well as verifying that your local DB is in sync (by running `mix ecto.dump` and verifying there's no git changes).
The second commit drops the old `disruption_day_of_weeks` table and recreates it with the `day_name` enum type. I also changed `disruption_id` to be NOT NULL, and added a unique constraint against disruption_id / day_name. If you look at the commit by itself, I think it shows the value of having the SQL schema, since the diff makes it pretty clear what's changing.

Change disruption_day_of_weeks to use day_name enum

---

.github/PULL_REQUEST_TEMPLATE.md
config/config.exs
lib/arrow/application.ex
lib/arrow/repo/migrator.ex
test/arrow/application_test.exs
test/arrow/repo/migrator_test.exs

The last deploy failed, I think because of the migration to change the day_of_weeks table. Normally, we migrate concurrently with the app starting up, but then the code has to be forwards/backwards compatible, and I didn't do that with those changes...
This adds a simple config flag to either run the migrations concurrently, or blocking during start-up (in which case they have to finish in < 5 seconds or the app won't start).
I deployed this branch, with `migrate_synchronously?: true` and it migrated and the deploy worked. So this branch isn't strictly necessary, but I figured it's useful to have as an option. I set the config value here to `false` (status quo), since we should generally have it that way, 
I also added our PR template that we use in other repos.

Add config to allow synchronous migrations if necessary

---

assets/src/jsonApiResource.ts
assets/src/jsonApiResourceObject.ts
assets/src/models/adjustment.ts
assets/src/models/dayOfWeek.ts
assets/src/models/disruption.ts
assets/src/models/exception.ts
assets/src/models/tripShortName.ts
assets/tests/models/disruption.test.ts

Fixes an issue in how we were serializing data for disruptions. Before it was like:
```
{
...
relationships: {
adjustments: [ { data: { adjustment data } }, {data: { adjustment data }} ]
...
}
}
```
But according to the spec, that's not right. There should be _one_ data field, and its contents should be either the resource data or an array of resource data objects:
```
{
...
relationships: {
adjustments: { data: [ { adjustment data}, {adjustment data} ] }
...
}
}
```
This means that there's really two ways to serialize an object: one, the encapsulated way, you'd use at the top level, and the other just the "data" part when embedding it in a relationship.
To the old `toJsonApi()` method I added a `toJsonApiData()` method for the other use case. Since all our models …

fix: toJsonApi() nesting of data fields

---

assets/src/app.tsx

Adding the `Switch` component ensures we render the first `Route` that matches rather than _all_ `Routes` that match.

fix: wrap Routes in Switch component

---

assets/src/api.ts
assets/src/disruptions/disruptionPreview.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/newDisruption.tsx
assets/src/disruptions/time.ts
assets/src/disruptions/viewDisruption.tsx
assets/src/jsonApi.ts
assets/src/models/disruption.ts
assets/src/models/exception.ts
assets/tests/api.test.ts
assets/tests/disruptions/disruptionPreview.test.tsx
assets/tests/disruptions/newDisruption.test.tsx
assets/tests/disruptions/time.test.ts
assets/tests/disruptions/viewDisruption.test.tsx
assets/tests/jsonApi.test.ts
assets/tests/models/disruption.test.ts
assets/tests/models/exception.test.ts
lib/arrow/adjustment.ex
lib/arrow/disruption.ex
lib/arrow_web/controllers/api/disruption_controller.ex
lib/arrow_web/router.ex
lib/arrow_web/utilities.ex
test/arrow/adjustment_test.exs
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/adjustment_controller_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs
test/arrow_web/utilities_test.exs

**Asana Ticket:** [🏹 API to create disruption, frontend uses it](https://app.asana.com/0/584764604969369/1157557244099553)
I'm still trying to finesse how I organize the frontend changes around the network call, for the purpose of abstraction and testing, but the functionality should be there, and I think the backend is done.
The commits to review in order:
* A small refactor to rename `apiCall` to `apiGet`, since my code works pretty differently. I plan to move my API calling logic into this module as `apiPost`, which should work fairly similarly, but will, e.g., look at different response statuses and take an error parser in addition to a success parser.
* The backend changes to accept a json:api POST and create the relevant records.
* The frontend changes for the `NewDisruption` …

Create disruption on frontend via API call

---

assets/src/disruptions/time.ts
assets/src/models/dayOfWeek.ts
assets/tests/disruptions/time.test.ts
assets/tests/disruptions/viewDisruption.test.tsx
assets/tests/jsonApi.test.ts
assets/tests/models/dayOfWeek.test.ts
assets/tests/models/disruption.test.ts

**Asana Ticket:** none
The "New Disruption" form was failing to create a disruption because it was sending `day: "tuesday"` over the wire, while the backend was expecting `day_name: "tuesday"`, consistent with the DB column. Rather than just changing the JSON serialization, I updated the model to have a `dayName` field, so it's referred to by the same term throughout the codebase.

fix: Frontend sends `day_name` like backend expects

---

assets/src/app.tsx
assets/src/disruptions/disruptionIndex.tsx
assets/src/disruptions/disruptionTable.tsx
assets/src/disruptions/time.ts
assets/src/jsonApi.ts
assets/src/models/dayOfWeek.ts
assets/tests/disruptions/disruptionIndex.test.tsx
assets/tests/disruptions/disruptionTable.test.tsx
assets/tests/disruptions/time.test.ts
assets/tests/jsonApi.test.ts
priv/repo/seeds.exs

**Asana Ticket:** [🏹 Arrow frontend uses API to load disruptions for index page](https://app.asana.com/0/584764604969369/1165773329683249/f)
Changes:
* add function `parseDaysAndTimes` in `/disruptions/time.ts`
* if single day, render `"{day}, {start_time} - {end_time}
* else if days are consecutive and all times are the same, render `"{first_day} - {last_day}, {start_time - end_time}"
* else if days are consecutive and all times are `undefined` besides the first day's `startTime` and/or the last day's `endTime`, render `"{first_day}, {start_time} - {last_day}, {end_time}`
* add component `DisruptionIndexConnected` responsible for fetching disruptions and parsing them into format expected by `DisruptionIndexView`
* update `toModelObject` to make sure we are only attaching an entity's …

feat: Disruption index page

---

assets/src/disruptions/disruptionIndex.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/newDisruption.tsx
assets/src/disruptions/time.ts
assets/src/disruptions/viewDisruption.tsx
assets/src/jsonApi.ts
assets/src/models/disruption.ts
assets/src/models/exception.ts
assets/tests/disruptions/editDisruption.test.tsx
assets/tests/disruptions/time.test.ts
assets/tests/jsonApi.test.ts
assets/tests/models/disruption.test.ts
assets/tests/models/exception.test.ts

**Asana Ticket:** Part of [🏹 API to edit disruption, frontend uses it](https://app.asana.com/0/584764604969369/1163421197919734/f)
This ended up being a fair bit of code that will be largely independent of the rest of the work on this ticket, so I decided to open a separate PR for it. It's all in one commit, unfortunately, but I don't think it's _too_ unwieldy to review.

feat: load disruption to front-end of edit page

---

assets/css/_datepicker.scss
assets/css/app.scss
assets/src/datePicker.tsx
assets/src/disruptions/disruptionTimePicker.tsx

**Asana Ticket:** [🏹 Date range selector should have a little calendar in it and placeholder text](https://app.asana.com/0/584764604969369/1158326786257801)
Mostly just a styling change. Since there are a few datepicker widgets on the new/edit forms, and they all use this, I assumed this would just be how our datepickers should look throughout the app. I created a new `DatePicker` component that basically wraps the underlying `react-datepicker` component and adds a font awesome icon next to it.
---
---

feat: Style date select with a little calendar

---

assets/src/api.ts
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/newDisruption.tsx
assets/tests/api.test.ts
assets/tests/disruptions/editDisruption.test.tsx
assets/tests/disruptions/newDisruption.test.tsx
lib/arrow/adjustment.ex
lib/arrow/disruption.ex
lib/arrow/disruption/day_of_week.ex
lib/arrow/disruption/exception.ex
lib/arrow/disruption/trip_short_name.ex
lib/arrow_web/controllers/api/disruption_controller.ex
lib/arrow_web/router.ex
priv/repo/seeds.exs
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [🏹 API to edit disruption, frontend uses it](https://app.asana.com/0/584764604969369/1163421197919734/f)
Commits should be reviewable individually. ~`apiPatch` is largely the same as `apiPost`, but I wasn't sure if it would make sense to combine them into a single function and, if so, what that function's name should be.~ Update: I consolidated it to `apiSend` per @losvedir's suggestion.

Edit disruption API

---

assets/package-lock.json
assets/package.json
assets/src/disruptions/disruptionIndex.tsx
assets/tests/disruptions/disruptionIndex.test.tsx
assets/tests/disruptions/disruptionPreview.test.tsx
assets/tests/disruptions/disruptionSummary.test.tsx
assets/tests/disruptions/disruptionTable.test.tsx
assets/tests/disruptions/disruptionTimePicker.test.tsx
assets/tests/header.test.tsx
assets/tests/loading.test.tsx
assets/tests/setup.ts
assets/tsconfig.json

**Asana Ticket:** [🏹 Transition existing Arrow tests from Enzyme to React Testing Library](https://app.asana.com/0/584764604969369/1170122874093785/f)
This is mostly pretty rote replacement of Enzyme with React Testing Library. The one bit I'm still not super happy with is the test `selecting a day of the week enables updating time range`. It used to do a lot of asserting based on the props of the component to make sure it was doing the right thing with the day of week time ranges. However, React Testing Library is a lot more opinionated about not really letting you pry into the contents of React components and instead preferring you to strictly test the front-end. I'm open to suggestions on how to re-do that test in a nicer way if anyone has any.

test: remove Enzyme, move existing tests to React Testing Library

---

lib/arrow/disruption.ex
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [[extra] Arrow - can't change days of week or trip short names, for disruption in past](https://app.asana.com/0/584764604969369/1172248816606377)
I realized another thing that should be immutable in the past: if the disruption's start date is in the past, then we shouldn't be able to change the days of week or trip short names on the disruption.

fix: Can't modify relationships if disruption start date is in past

---

assets/package-lock.json

The dependabot PR #266 breaks the build because of an error in `@testing-library/react`, for which I opened an [issue](https://github.com/testing-library/react-testing-library/issues/694).
The authors don't plan to make changes to `@testing-library/react` that would make it pass from upgrading that package alone. However, by explicitly adding `pretty-format` as a dependency of our own, it makes that PR pass.
The authors suggest blowing away `package-lock.json` and recreating, and somehow this does actually fix it. That feels like a sledgehammer and should be a non-starter, but.... I did it and the app seems to work fine. Since we're still early in the development maybe it's worthwhile to do. It appears to have pulled in a _lot_ of upgrades, which I'm confused about …

chore: Update deps by blowing away package-lock and re-installing

---

lib/arrow_web/router.ex
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [🏹 move arrow /disruptions route out of authenticated pipeline](https://app.asana.com/0/584764604969369/1183529627515231/f)

chore: remove authentication on Disruption index route

---

assets/src/disruptions/disruptionPreview.tsx
assets/src/disruptions/newDisruption.tsx
assets/src/disruptions/viewDisruption.tsx
assets/tests/disruptions/disruptionPreview.test.tsx
assets/tests/disruptions/newDisruption.test.tsx
assets/tests/disruptions/viewDisruption.test.tsx
lib/arrow_web/utilities.ex
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [🏹 Ability to add trip short names for CR disruptions in Arrow](https://app.asana.com/0/584764604969369/1173526948047141/f)

feat: add ability to add trip short names to disruption

---

priv/repo/shuttles.json

**Asana Ticket:** Partial fulfilment of [🚧 Green-E shuttle August](https://app.asana.com/0/584764604969369/1185335758800835/f)
Related gtfs_creator pull request: https://github.com/mbta/gtfs_creator/pull/967.
Wish we could see just the diff.
Here's what was added:
```
{"id": "HeathStreetPrudential", "attributes": {"route_id": "Green-E"}},
```
- [] Any new or changed functions have typespecs

feat: Add Prudential–Heath Street shuttle

---

.tool-versions

This was accidentally introduced in 1a3ab6c3.

fix: remove Python from .tool-versions

---

config/config.exs
config/prod.exs
lib/arrow_web/try_api_token_auth.ex
lib/fake/ex_aws.ex
test/arrow_web/try_api_token_auth_test.exs
test/arrow_web/utilities_test.exs
test/support/helper.ex

**Asana Ticket:** [🏹 When authenticating with API token, check that user is still in arrow-admin groupE](https://app.asana.com/0/584764604969369/1184693457899858/f)
Gets the list of groups from the API and passes it along. Steps further along the authentication pipeline will make sure that the `arrow-admin` group is present if needed. I ended up referencing the somewhat-dusty `ex_aws_cognito` library code [here](https://github.com/omt-tech/ex_aws_cognito/blob/master/lib/ex_aws/cognito_idp.ex#L390-L397) as inspiration (thanks @ianwestcott for pointing me to that file).

Get user groups from Cognito API when using API token

---

test/mix/tasks/copy_db_test.exs

a few assertions relied on dates determined by the current day, which isn't deterministic.

fix: copy db test to not use hardcoded dates

---

assets/src/disruptions/disruptionCalendar.tsx
assets/tests/disruptions/disruptionCalendar.test.tsx

Problem: the `rrule` library we use to make recurring calendar events will create an event for all days in a range if you supply an empty list for the `byweekday` option, which meant that disruptions created without days of week would be displayed for the entire range even though it would not be applied in `gtfs_creator`
Solution: simply do not create any calendar events if the disruption has no days of week.
Added a change to the sample test data and confirmed that no event was created or displayed on the calendar.

fix: do not show disruptions on calendar if they have no days_of_week

---

assets/src/disruptions/disruptionCalendar.tsx
assets/src/jsonApi.ts
assets/src/models/disruption.ts
assets/src/models/exception.ts
assets/tests/disruptions/disruptionCalendar.test.tsx
assets/tests/jsonApi.test.ts
assets/tests/models/disruption.test.ts
assets/tests/models/exception.test.ts

**Asana Ticket:** [[extra] fix bug in Arrow calendar dates after 11/1](https://app.asana.com/0/584764604969369/1188024321662505/f)
Problem: We were not handling the quirks of the [`rrule`](https://github.com/jakubroztocil/rrule#important-use-utc-dates) library correctly, which caused dates to be off after daylight savings on 11/1/2020.
> The bottom line is the returned "UTC" dates are always meant to be interpreted as dates in your local timezone. This may mean you have to do additional conversion to get the "correct" local time with offset applied.
Solution: convert dates provided to `rrule` following the example in the library's README
```
// RIGHT: Will produce dates with recurrences at the correct time
new RRule({
freq: RRule.MONTHLY,
dtstart: new Date(Date.UTC(2018, 1, 1, 10, 30)), …
```

fix: use UTC dates for calendar

---

lib/arrow/disruption.ex
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [🏹 Validation to fill out all relevant form inputs](https://app.asana.com/0/584764604969369/1186709623846987/f)
Simply added `validate_length(:days_of_week, min: 1)` to the `Disruption` changeset and added/updated tests accordingly.

fix: add validation to require at least one DayOfWeek

---

assets/tests/disruptions/disruptionCalendar.test.tsx

Merged in an out-of-date branch and missed adding an `id` after making it required in a prior commit.

fix: linter error

---

assets/src/disruptions/disruptionTimePicker.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/models/disruption.ts
assets/src/models/exception.ts
assets/tests/models/disruption.test.ts

**Asana Ticket:** [🏹 Sort exception dates when displaying / editing disruptions](https://app.asana.com/0/584764604969369/1188017252062513/f)
Changes:
* sort `Exceptions` in `Disruption.fromJsonObject`, which flows through to the detail and edit pages
* Also noticed and fixed an issue introduced by https://github.com/mbta/arrow/pull/380, converting dates back from UTC when providing them to `DatePicker` component (the `react-datepicker` library appears to [rely on the local timezone](https://github.com/gpbl/react-day-picker/issues/130)).

fix: sort exception dates

---

assets/src/datePicker.tsx
assets/src/disruptions/disruptionTimePicker.tsx

Follow up to https://github.com/mbta/arrow/pull/392, applying the same fix to Disruption date range inputs, this time just moving the date conversion into the logic our wrapper component.

fix: convert all dates provided to DatePicker component into UTC dates

---

config/releases.exs
lib/arrow/repo.ex
semaphore/credo.sh
test/arrow/repo_test.exs

**Asana Ticket:** [🏹 Reconnect after DB authentication changes](https://app.asana.com/0/584764604969369/1186678199122409)
The fix here is actually pretty simple. `Ecto.Repo` options are passed to the `Postgrex` adaptor which are passed to [`DBConnection`](https://hexdocs.pm/db_connection/DBConnection.html#start_link/2), which has a nice `:configure` option which takes a MFA tuple for a function it should call before each time it tries to connect.
By moving the `ex_aws_rds` logic into that function, the actual configuration of the DB can now be done with the usual, simple `config :arrow, Arrow.Repo, ...` approach. Since the prod environment will pull from environment variables, I made a `releases.exs` file for `mix release` to use.
I confirmed that I could induce the `PAM authentication …

fix: Regenerate AWS IAM auth token on connect

---

assets/css/_disruption_list_container.scss
assets/css/app.scss
assets/src/app.tsx
assets/src/disruptions/disruptionCalendar.tsx
assets/src/disruptions/disruptionIndex.tsx
assets/src/disruptions/disruptionListContainer.tsx
assets/src/disruptions/disruptionNeedsReview.tsx
assets/src/disruptions/disruptionTable.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/newDisruption.tsx
assets/src/disruptions/viewDisruption.tsx
assets/src/page.tsx
assets/tests/disruptions/__snapshots__/disruptionCalendar.test.tsx.snap
assets/tests/disruptions/disruptionListContainer.test.tsx
assets/tests/page.test.tsx

**Asana Ticket:** [🏹 Navigation bar with disruption and review pages ](https://app.asana.com/0/584764604969369/1185700222235219/f)
Changes:
* Added `DisruptionListContainer` component containing the new navigation links, which can wrap `DisruptionIndex`, the coming "Needs Review" page or any other page we'd want to have those links for
* Pulled out the logic we had rendering `Header` in each individual page into a `Page` wrapper that handles it for us
* Some small style tweaks

feat: add nav links to toggle between published and draft disruption views

---

assets/src/disruptions/disruptionIndex.tsx
lib/arrow/disruption.ex
lib/arrow/disruption_revision.ex
lib/arrow_web/controllers/api/disruption_controller.ex
lib/arrow_web/controllers/temp_review_changes_controller.ex
lib/arrow_web/router.ex
lib/arrow_web/templates/temp_review_changes/index.html.eex
lib/arrow_web/views/temp_review_changes_view.ex
test/arrow/disruption_revision_test.exs
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs
test/arrow_web/controllers/temp_review_changes_controller_test.exs
test/support/factory.ex

**Asana Ticket:** [🏹 Arrow distinguishes between published and draft versions](https://app.asana.com/0/584764604969369/1185700222235213/f)
This one is probably most easily-reviewed on a commit-by-commit basis, and the order of the commits should match the order of the acceptance criteria bullet points on the ticket.

Distinguish published / draft disruptions

---

assets/css/_disruption_view_toggle.scss
assets/css/app.scss
assets/package-lock.json
assets/package.json
assets/src/disruptions/viewDisruption.tsx
assets/src/disruptions/viewToggle.tsx
assets/tests/disruptions/viewDisruption.test.tsx

**Asana Ticket:** [🏹 Disruption detail page has draft and published versions](https://app.asana.com/0/584764604969369/1186492610975121/f)
* added reusable `useDisruptionViewParam` custom hook to extract the active view from a query param
* added reusable `DisruptionViewToggle` component that sets the appropriate query param
* added `DisruptionViewToggle` to `ViewDisruption` component, and used `useDisruptionViewParam` to conditionally add `published_only=true/false` to GET request

feat: add ability to toggle between draft and published versions on disruption details page

---

assets/src/disruptions/disruptionCalendar.tsx
assets/src/disruptions/disruptionIndex.tsx
assets/src/disruptions/disruptionTable.tsx
assets/src/disruptions/viewDisruption.tsx
assets/tests/disruptions/disruptionCalendar.test.tsx
assets/tests/disruptions/disruptionIndex.test.tsx
assets/tests/disruptions/disruptionTable.test.tsx
assets/tests/disruptions/viewDisruption.test.tsx

Follow up to https://github.com/mbta/arrow/commit/643af75851bab92029aa57aadb3fc45c966cf747, adding the correct query param on detail page links so the user arrives on the page with the correct view enabled.

fix: conditionally add v=draft query param to detail page links on homepage

---

lib/arrow_web/controllers/api/disruption_controller.ex
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** Followup to [🏹 Arrow distinguishes between published and draft versions](https://app.asana.com/0/584764604969369/1185700222235213/f)
After some discussion, realized we should be treating an empty query param as falsy. Also broke out the `?only_published=false` case into its own test to match what I did for `index/2`.

fix: accept empty string for only_published query param

---

lib/arrow/disruption_revision.ex
test/arrow/disruption_revision_test.exs

**Asana Ticket:** [[extra] Fix deletion of disruptions not being reflected in pending changes](https://app.asana.com/0/584764604969369/1191193425257601/f)

fix: exclude deleted disruptions in latest_revision

---

assets/.eslintrc.js

I find this rule kind of annoying. To me, objects (even object literals) don't conceptually have an ordering to their keys.

chore: Disable object-literal-sort-keys lint

---

assets/src/disruptions/disruptionTable.tsx
assets/tests/disruptions/disruptionTable.test.tsx

**Asana Ticket:** [[extra] sort Arrow adjustment labels in table view](https://app.asana.com/0/584764604969369/1194957087550849)
In the attached screenshot, you'll see two separate rows where there should be a rowlette. This is because the adjustments were saved in different orders for each revision, for whatever reason. This just fixes the logic to sort the adjustments before [comparing whether labels are equal](https://github.com/mbta/arrow/blob/fl/fix-adjustments-sorting/assets/src/disruptions/disruptionTable.tsx#L222), and thus whether we should show a rowlette or new labels.

fix: sort adjustments for equality comparison

---

assets/src/disruptions/disruptionIndex.tsx
assets/tests/disruptions/disruptionIndex.test.tsx

This just deletes the published/ready filter. The "needs review" and other filters will continue work as before.

chore: remove "published/ready" status filter

---

assets/css/_base.scss
assets/css/_disruption_details.scss
assets/css/_overrides.scss
assets/css/app.scss
assets/src/disruptions/disruptionTable.tsx
assets/src/disruptions/editDisruption.tsx
assets/src/disruptions/time.ts
assets/src/disruptions/viewDisruption.tsx
assets/src/disruptions/viewToggle.tsx
assets/src/header.tsx
assets/src/models/disruption.ts
assets/tests/disruptions/disruptionTable.test.tsx
assets/tests/disruptions/viewDisruption.test.tsx
assets/tests/models/disruption.test.ts

**Asana Ticket:** [🏹 Detail page updates](https://app.asana.com/0/584764604969369/1195117716558252/f)
Changes: mostly cosmetic changes and a few new features and changes to logic:
* added `draftRevision` as an optional attribute, set while parsing in `fromJsonObject` (like `draftRevision` and `readyRevision`
* added `getUniqueRevisions` function that returns `{published: DisruptionRevision | null, ready: ...}`, to make it more convenient to do the "rolling up" of revisions
* added `uniqueRevisionFromDisruptionForView` function, which takes unique revisions and returns one matching the supplied view
* added a button to "mark as ready" from details page
* added proper view params `?v=draft | ready | published` on homepage links and redirects from create/edit pages

feat: Detail page updates

---

assets/src/confirmationModal.tsx
assets/src/disruptions/disruptionIndex.tsx
assets/src/disruptions/viewDisruption.tsx
assets/tests/disruptions/disruptionIndex.test.tsx
assets/tests/disruptions/viewDisruption.test.tsx

**Asana Ticket:** [🏹 Detail page updates](https://app.asana.com/0/584764604969369/1195117716558252/f)
Follow up to https://github.com/mbta/arrow/pull/443, adding custom confirmation modal. Added this to:
* Index page (when marking revisions as ready)
* Details page (when marking revision as ready and when deleting)
Additionally, a couple of small refactors:
* in `DisruptionIndexView` component, use `Disruption.getUniqueRevisions` introduced in [#443](https://github.com/mbta/arrow/pull/443/files#diff-5214aebede4a1c4d16005ce49bd4ead5R120)
* Change logic in `anyMatchesFilter` to filter out disruptions with no active revision. Short term fix to clean up the table view. Still would have the problem where a deleted "ready" revision is not marked as "published", so the "published" revision would …

feat: custom confirmation modal

---

assets/.eslintrc.js
assets/package-lock.json
assets/package.json
assets/src/disruptions/disruptionCalendar.tsx
assets/src/models/dayOfWeek.ts

**Asana Ticket:** [💳 Add eslint-plugin-import](https://app.asana.com/0/584764604969369/1194650366902593/f)
Added module `eslint-plugin-import` and added two rules:
* Ensure all exports appear after other statements
* Prefer named exports to be grouped together in a single export declaration
Note I did **not** add a rule forbidding `default` exports, which is another possibility, though would require changing many files.

refactor: add lint rule to declare module exports at end of file

---

lib/arrow/db_structure.ex
test/arrow/db_structure_test.exs

**Asana Ticket:** Unrelated, but to help debug [🐛 Unable to edit disruption in Arrow](https://app.asana.com/0/281253957434160/1198920748926221)
A few tweaks to the `mix copy_db` task.
* The first commit adds `last_published_at` to the list of columns to copy over.
* The second commit is a refactor of the table structure. It switches the table definition from a list of tuples to a new struct `Arrow.DbStructure.Table`, to prepare for adding a new configuration option of columns that use sequences and the names of the sequences.
* The third commit adds a step to the import to query the columns that use auto-generated sequence values to get their current max value and then to reset their sequence generator to start higher than that.

mix copy_db fixes

---

lib/arrow_web/controllers/api/disruption_controller.ex
test/arrow_web/controllers/api/disruption_controller_test.exs

**Asana Ticket:** [🐛 Unable to edit disruption in Arrow](https://app.asana.com/0/281253957434160/1198920748926221)
The fix is pretty small. Basically, the `update` controller action used `DisruptionRevision.only_ready()` to select the latest "ready" revision to clone when updating. However, I think actually we should be cloning the latest revision. The frontend flow lets you edit only based off the latest draft. And the current flow causes a crash if a given disruption doesn't have a ready revision yet, but is updated (i.e.: two drafts in a row before any approvals).

fix: Update disruptions that aren't ready

---

assets/src/disruptions/disruptionDateRange.tsx
assets/src/disruptions/disruptionExceptionDates.tsx
assets/tests/disruptions/disruptionExceptionDates.test.tsx
assets/tests/disruptions/editDisruption.test.tsx

**Asana Ticket:** [🏹 date fields are more user friendly](https://app.asana.com/0/584764604969369/1199117764695509/f)
* set `autoComplete="off"` prop to disable the browser's autocomplete
* treat the "new" exception date input the same as the existing exception dates, only conditionally showing/hiding the "add new exception" button based on `isAddingException`, so that we don't unmount the "new" exception date input when the user types a number (which `react-datepicker` treats as selecting a date).

fix: exception datepicker

---

assets/package-lock.json
assets/src/disruptions/disruptionIndex.tsx
assets/tests/disruptions/disruptionIndex.test.tsx
package-lock.json

**Asana Ticket:** [🐛 Arrow: multiple revisions of disruption show up simultaneously in calendar view](https://app.asana.com/0/584764604969369/1199340421679669)
If a disruption had a ready and/or draft revision, each of those would display as its own "event" on the calendar along with the published one. This was due to how the filtering logic used in the table view, which always displays all revisions of "matched" disruptions, was carried over to the calendar view.

fix: duplicate events in calendar view

---

semaphore/build_push.sh

I really should have test-deployed the last branch to dev _before_ merging it 😑 This would also go away once the Docker Hub variables are set up for this project, but in any case the script should work if they're not present.

fix: "unbound variable" error in build script

---

assets/src/disruptions/disruptionIndex.tsx
assets/tests/disruptions/disruptionIndex.test.tsx

**Asana Ticket:** [🐛 Disruptions marked for deletion should appear in Needs Review filter](https://app.asana.com/0/584764604969369/1199550046000729)
The "needs review" filter only matches revisions that are in draft status. Separately, if a revision was deleted (`isActive === false`), it would not match any filters regardless of status. This meant disruptions with a drafted deletion didn't appear in "needs review" at all, since the draft revision was excluded by the `isActive` filter and the other revisions were excluded by the "needs review" filter.
This addresses the issue by having the universal `isActive` filter only exclude revisions that are published.

fix: pending deletions missing from "needs review"

---

Dockerfile

**Asana Ticket:** [💳 update arrow to use hexpm/elixir container](https://app.asana.com/0/0/1200075745309243/f)
Similar to mbta/prediction_analyzer#432, this pins the Erlang version used when building the application in the Docker container using a hexpm/elixir image. `curl`, `git`, and `ca-certificates` had to be installed as well. This branch is currently deployed to dev.

chore: pin Erlang version in Docker

---

.envrc.example
.gitignore
README.md
config/dev.exs
config/test.exs
lib/arrow_web/auth_manager/error_handler.ex
lib/arrow_web/controllers/api/db_dump_controller.ex
lib/arrow_web/controllers/auth_controller.ex
lib/arrow_web/controllers/my_token_controller.ex
lib/arrow_web/controllers/temp_review_changes_controller.ex
lib/arrow_web/ensure_arrow_group.ex
lib/arrow_web/try_api_token_auth.ex
test/arrow_web/controllers/api/db_dump_controller_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs
test/arrow_web/controllers/api/notice_controller_test.exs
test/arrow_web/controllers/auth_controller_test.exs
test/arrow_web/controllers/my_token_controller_test.exs
test/arrow_web/controllers/page_controller_test.exs
test/arrow_web/controllers/temp_review_changes_controller_test.exs
test/arrow_web/controllers/unauthorized_controller_test.exs
test/arrow_web/try_api_token_auth_test.exs

A couple of miscellaneous things that caught my attention on the way to the (de-)SPA:
* Add `direnv` for greater convenience of specifying your own database username (with Homebrew the default Postgres username is your system username, not `postgres`)
* We were doing a lot of extra typing in some instances where we could take advantage of the default Phoenix aliases and imports

Direnv support and refactor using aliases/imports

---

assets/tests/disruptions/disruptionIndex.test.tsx

This test meant to create a 7-day date span, but used "today + 7 days" rather than "today + 6 days", so the end date fell on the same day of the week as the start date. Since the test disruption was active on Monday, when the current day was Monday this caused the disruption to appear in the calendar twice, failing the test.

test: fix calendar test failing on Mondays

---

Dockerfile

Buster is no longer the current stable release of Debian, causing an error when running `apt-get update` in an image built when Buster _was_ the stable release:
```
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
```
The `--allow-releaseinfo-change` option allows the update to continue.
* [Failed deployment of `master`](https://github.com/mbta/arrow/actions/runs/1139595707)
* [Successful deployment of this branch](https://github.com/mbta/arrow/actions/runs/1139760603)

ci: fix deploy failing on new Debian release

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
lib/arrow/adjustment.ex
lib/arrow_web/controllers/disruption_controller.ex
lib/arrow_web/controllers/disruption_controller/index.ex
lib/arrow_web/views/disruption_view/form.ex
test/arrow/adjustment_test.exs
test/arrow_web/views/disruption_view/form_test.exs

**Asana:** [🏹 Adjustments shown with spaces aka "pretty name" ](https://app.asana.com/0/584764604969369/1200681721075711)

Space out adjustment names in select box

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
test/integration/disruptions_test.exs

**Asana:** [🏹 Weekday disruptions have default start time of 845pm ](https://app.asana.com/0/881264583703207/1200908109398090)

feat: default time range for subway disruptions

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
lib/arrow/disruption_revision.ex
lib/arrow_web/controllers/disruption_controller.ex
lib/arrow_web/templates/feed/disruption_summary.html.eex
lib/arrow_web/views/disruption_view/form.ex
priv/repo/migrations/20210921192435_add_row_status.exs
priv/repo/structure.sql
test/arrow/disruption_test.exs
test/arrow_web/controllers/disruption_controller_test.exs
test/arrow_web/views/disruption_view/form_test.exs
test/integration/disruptions_test.exs

**Asana Ticket:** [🏹 Add ROW status concept](https://app.asana.com/0/584764604969369/1200687441670232)
Adds the concept of "ROW status" to the app, where a Disruption (revision) can be either approved or pending. A subsequent PR will update GTFS Creator to ignore pending disruptions.

feat: Add ROW status concept

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
lib/arrow/db_structure.ex
lib/arrow/disruption_revision.ex
lib/arrow_web/templates/disruption/_table.html.eex
lib/arrow_web/templates/disruption/show.html.eex
lib/arrow_web/templates/feed/disruption_summary.html.eex
lib/arrow_web/views/api/disruption_revision_view.ex
lib/arrow_web/views/disruption_view/form.ex
priv/repo/migrations/20210922191945_row_status_name_change.exs
priv/repo/structure.sql
test/arrow/db_structure_test.exs
test/arrow/disruption_test.exs
test/arrow_web/controllers/disruption_controller_test.exs
test/arrow_web/views/disruption_view/form_test.exs
test/integration/disruptions_test.exs

Tweaks and fix-ups to #769.
The largest change is renaming the column from `row_confirmed` to `row_approved`. I don't know where I got "confirmed" in my head before, but the mocks are pretty consistent in calling it "approved". The presentation layer doesn't *have* to match exactly the data layer, but might as well get started off on the right foot.
I added `row_approved` to a few more places: The API that gtfs_creator uses, `clone!`, `db_structure`, a type spec.
I added a simple `approval status` to the show page. I found mocks to a version of the show page we'll have in the future with a sidebar with notes and some other things. So I didn't copy the design exactly, which won't work now, but I did use the wording. I made a couple tickets regarding that mock to make …

fix: ROW status tweaks

---

lib/arrow/disruption.ex
lib/arrow/disruption_revision.ex
lib/arrow_web/controllers/disruption_controller.ex
test/arrow_web/controllers/api/disruption_controller_test.exs

Docs: https://hexdocs.pm/ecto/3.7.1/Ecto.Schema.html#module-reflection
This avoids duplicating all the field names of revisions and their associations, so we don't have to remember to also update the clone function whenever a field is added or removed.
By creating a changeset for the clone instead of immediately saving it to the database, we also avoid the need to wrap updates and deletes in a transaction.
We still duplicate the names of associations — theoretically we could also avoid this with introspection, but it's less clear that doing so would be worth the complexity.

refactor: use introspection to clone revisions

---

lib/arrow_web/templates/disruption/_table.html.eex
lib/arrow_web/views/disruption_view.ex

**Asana Ticket:** [ROW status on table](https://app.asana.com/0/584764604969369/1200687441670236/f)
Removed the `published?` function from the index view. The table now colors rows and renders the approval icon based on the new `disruption_revision.row_status` column.

feat: table shows ROW status

---

.github/workflows/ci.yml

**Asana Ticket:** [Pin Postgres version in CI](https://app.asana.com/0/584764604969369/1201107259989900/f)
Simple update, the `postgres` service in our CI workflow now uses `postgres:11` instead of just `postgres`, which tells Docker to pull `postgres:latest` by default. This should fix `master`.

fix: pin Postgres version used in CI

---

lib/arrow_web/controllers/disruption_controller/filters.ex
lib/arrow_web/controllers/disruption_controller/filters/table.ex
lib/arrow_web/controllers/disruption_controller/index.ex
lib/arrow_web/templates/disruption/index.html.eex
test/arrow_web/controllers/disruption_controller/filters_test.exs
test/arrow_web/controllers/disruption_controller/index_test.exs
test/integration/disruptions_test.exs

**Asana Ticket:** [ROW status can be filtered](https://app.asana.com/0/584764604969369/1200689411100427/f)
Added a new filter for both the table and calendar views that when activated, only shows ROW approved disruptions.

feat: filtering by ROW status

---

mix.exs

**Asana Ticket:** [fix Arrow coverage reporting](https://app.asana.com/0/584764604969369/1201120775201216/f)
Tells Lcov to ignore the `deps/` path when generating coverage info. We don't want `deps/mox/lib/mox.ex` covered and it breaks coverage reporting.

fix: don't generate coverage data for deps/

---

assets/css/disruption_calendar.css
lib/arrow_web/views/disruption_view/calendar.ex
test/arrow_web/views/disruption_view/calendar_test.exs

**Asana:** [🏹 Disruptions can be created without adjustment](https://app.asana.com/0/584764604969369/1200681721075715)
We didn't say much in the task about _how_ these disruptions should be shown on the calendar, so I made up a distinct appearance for them and used the disruption ID as the title, to provide a way to distinguish between multiple disruptions with no adjustments (and since we already use disruption IDs prominently elsewhere in the UI).

feat: show no-adjustments disruptions on calendar 

---

assets/css/disruption_calendar.css
lib/arrow_web/views/disruption_view/calendar.ex
test/arrow_web/views/disruption_view/calendar_test.exs

**Asana Ticket:** [🏹 ROW status on calendar](https://app.asana.com/0/584764604969369/1200687441670238/f)
[Includes changes in css file for added color events, associated with pending disruption status vs approved disruption status. Change is picked up in DCalendar template.]

chore: Added color feature for pending disruption status

---

assets/css/disruption_calendar.css

**Asana Ticket:** [[extra] font color change for pending disruptions on arrow calendar](https://app.asana.com/0/584764604969369/1201481447960456/f)
Added css color event for text of pending disruption status.

fix: Text color for pending disruptions on calendar

---

lib/arrow_web/controllers/disruption_controller/filters/table.ex
lib/arrow_web/controllers/disruption_controller/index.ex
test/arrow_web/controllers/disruption_controller/filters_test.exs
test/arrow_web/controllers/disruption_controller/index_test.exs

**Asana:** extra task — noticed this while implementing #818
The ability to explicitly select this sort was removed in #770, but it was still supported and used as the default sort, despite adjustment labels no longer appearing in the table. This changes the default sort to ascending by start date, the only remaining sort other than ID. It's a somewhat arbitrary choice, but we can always change it to ID if feedback indicates that's a more useful default.
We agreed this should be updated somehow during a [Slack conversation](https://mbta.slack.com/archives/CF9QKK2AF/p1632510493307200) a while back, but I can't find any Asana tasks that might have been created from it. The same conversation also mentions making the search feature work with descriptions — for that, see #820.

refactor: remove `source_label` table sort

---

lib/arrow_web/controllers/disruption_controller/index.ex
test/arrow_web/controllers/disruption_controller/index_test.exs

**Asana:** extra task — noticed this while implementing #818 
When "descriptions" were introduced in #770 and took the place of adjustment labels in the index table, the search feature was not updated to search within them. Now it does.
We agreed this should be updated during a [Slack conversation](https://mbta.slack.com/archives/CF9QKK2AF/p1632510493307200) a while back, but I can't find any Asana tasks that might have been created from it. The same conversation also mentions cleaning up the default table sorting — for that, see #819.
Open question: This updates the search function to search descriptions _in addition to_ adjustment labels. Should it search _only_ in descriptions? On the one hand, searching within a field that isn't shown anywhere in the results could be confusing …

feat: include descriptions in index search

---

assets/css/app.css
assets/css/disruption_form.css
assets/css/notes.css
assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
config/config.exs
lib/arrow/disruption.ex
lib/arrow/disruption/note.ex
lib/arrow/disruption_revision.ex
lib/arrow_web/controllers/disruption_controller.ex
lib/arrow_web/controllers/note_controller.ex
lib/arrow_web/router.ex
lib/arrow_web/templates/disruption/_note.html.heex
lib/arrow_web/templates/disruption/edit.html.heex
lib/arrow_web/templates/disruption/new.html.heex
lib/arrow_web/templates/disruption/show.html.heex
lib/arrow_web/views/disruption_view.ex
lib/arrow_web/views/disruption_view/form.ex
lib/arrow_web/views/error_helpers.ex
priv/repo/migrations/20220105203850_disruption_notes.exs
priv/repo/structure.sql
test/arrow/disruption/note_test.exs
test/arrow/disruption_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs
test/arrow_web/controllers/disruption_controller_test.exs
test/arrow_web/controllers/note_controller_test.exs
test/arrow_web/views/disruption_view/form_test.exs
test/integration/disruptions_test.exs
test/support/factory.ex

**Asana Ticket:** [🏹 Notes can be added to a disruption](https://app.asana.com/0/584764604969369/1201330656931525)
This adds the concept of "notes" to the app. Notes can be added from a form on the show page (if the user is an admin), or while creating or updating a disruption.
This PR can be reviewed commit-by-commit. The commits are:
1. Set up the data model. Notes belong to a disruption (not a revision).
2. Add notes from a form on the show page.
3. A refactor of `Disruption.create` and `Disruption.update` to switch to using `Ecto.Multi` in preparation for the next commit which adds notes. I went back and forth here and tried a few different approaches and liked this one the best. The main consideration is that the Ecto docs and the book *Programming Ecto* (which I bought and read …

feat: Add "notes" to disruptions

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
lib/arrow_web/templates/disruption/show.html.heex
test/arrow_web/controllers/disruption_controller_test.exs
test/integration/disruptions_test.exs

Per discussion in #829, we decided to just hide the Notes feature altogether for now.
In terms of what "hide" means, I did a fairly minimal approach of removing the form from the page, but the controller and DB side of things are still there. Another approach could have been a complete rip-out or revert of the Notes feature, but I actually kind of liked some of the refactors in that PR. Plus, while we're putting Arrow work on ice for now, I hope that in the future we'll come back to it, and we can enable notes then, along with the infrastructure/AD work. Also, this was quick and I just want to be done with this saga....

fix: Hide notes feature for now

---

.github/workflows/ci.yml
.github/workflows/deploy-ecs.yml
.tool-versions
Dockerfile
assets/package-lock.json

This PR updates the deploy workflow to use v2 of the `deploy-ecs` workflow. This updated workflow assumes an IAM role instead of relying on long-lasting AWS keys for an IAM user
Note the run failure, which appears to have been happening for a while and is not due to these changes.

Chore: Convert workflow to v2

---

Dockerfile

fix: update SHA256 for AWS cert

---

assets/src/components/DisruptionForm.tsx
assets/tests/components/DisruptionForm.test.tsx
lib/arrow/disruption_revision.ex
lib/arrow_web/controllers/disruption_controller.ex
test/arrow/disruption_test.exs

**Asana Ticket:** No Ticket
In https://github.com/mbta/arrow/commit/a639ec8d25e94c04cd05c2e3c951143c77e56896, `plug` was updated to `1.15.2`, where [version 1.5.0](https://github.com/elixir-plug/plug/blob/main/CHANGELOG.md#v1150-2023-10-01) changed how URL encoded parameters in the form of `param[][field]` are handled. The solution is either to use parameters in the form of `param[field][]` or `param[index][field]`. This PR updates all such usages to be compatible with the new parser.

fix: fix parameter parsing after plug update

---

README.md
assets/package-lock.json
config/config.exs
lib/arrow/permissions.ex
lib/arrow_web/controllers/api/db_dump_controller.ex
lib/arrow_web/controllers/api/notice_controller.ex
lib/arrow_web/controllers/my_token_controller.ex
lib/arrow_web/router.ex
test/arrow_web/controllers/api/adjustment_controller_test.exs
test/arrow_web/controllers/api/disruption_controller_test.exs
test/arrow_web/controllers/my_token_controller_test.exs

**Asana Ticket:** [💳 Fix Dependabot CI on gtfs_creator](https://app.asana.com/0/584764604969369/1206364138902694)
Related to https://github.com/mbta/arrow/pull/963 in that we need the GET APIs to support non-admin users for dependabot 
Partly based on https://github.com/mbta/arrow/pull/930 with other updates since then.

feat: non-admins can fetch their token and use GET apis

---

config/config.exs
lib/arrow_web/try_api_token_auth.ex
lib/arrow_web/try_api_token_auth/local.ex
priv/repo/migrations/20240207224211_add_ci_readonly_user_token.exs
priv/repo/structure.sql
test/arrow_web/try_api_token_auth/local_test.exs
test/arrow_web/try_api_token_auth_test.exs

**Asana Ticket:** [💳 Fix Dependabot CI on gtfs_creator](https://app.asana.com/0/584764604969369/1206364138902694)
* Adds a new api login module for a token-only read-only user (username/token database entry)
* Adds a migration to add a token-only read-only user for dependabot

feat: add login via token for API user for dependabot

---

lib/arrow_web/controllers/auth_controller.ex
lib/arrow_web/templates/layout/app.html.heex

Meets our best practices of not putting the URL in the Guardian claim, as we can run into errors where the cookie gets too large.
s/o to @firestack who pointed this out.

feat: move `logout_url` to the session

---

config/config.exs
config/dev.exs
config/prod.exs
config/runtime.exs

**Asana Ticket:** [🏹  Implement Shuttle Route KML Save to S3](https://app.asana.com/0/584764604969369/1207423464713208/f)
Depends on infra PR
* Use a dedicated s3 prefix environment variable from the app env to match s3 permissioning in [🏹 Create Arrow S3 bucket](https://app.asana.com/0/584764604969369/1207404453434865)

feat: add runtime configuration of S3_PREFIX from app environment

---

lib/mix/tasks/copy_db.ex

**Asana Ticket:** ad hoc
https://mbta.slack.com/archives/C07639BHFKR/p1724686373999939

tweak: Register atoms earlier in execution of `mix copy_db`

---

priv/repo/migrations/20240826153959_create_gtfs_tables_part1.exs
priv/repo/migrations/20240826154124_create_gtfs_tables_part2.exs
priv/repo/migrations/20240826154204_create_gtfs_tables_part3.exs
priv/repo/migrations/20240826154208_create_gtfs_tables_part4.exs
priv/repo/migrations/20240826154213_create_gtfs_tables_part5.exs
priv/repo/migrations/20240826154218_create_gtfs_tables_part6.exs

**Asana Ticket:** [Define DB table schemata for GTFS data](https://app.asana.com/0/584764604969369/1208141467238946/f)
(first subtask of [[extra] 🏹 Implement /import-GTFS Arrow endpoint](https://app.asana.com/0/584764604969369/1207472819136817/f))
This is split into several migrations, partly to keep file lengths reasonable and partly to make it clear which tables reference/depend on the existence of other tables.
<details>
<summary><h4>Output of <code>mix ecto.migrate --log-migrations-sql</code></h4></summary>
```sql
11:27:58.114 [info] == Running 20240826153959 Arrow.Repo.Migrations.CreateGtfsTablesPart1.change/0 forward
11:27:58.117 [info] create table gtfs_agencies
11:27:58.137 [debug] QUERY OK db=18.8ms
CREATE TABLE "gtfs_agencies" ("id" integer, "name" varchar(255) NOT NULL, "url" …
```

feat: Create tables for GTFS-static archive import

---

.github/workflows/ci.yml
lib/arrow/shuttle/stop.ex
lib/arrow_web/controllers/stop_controller.ex
lib/arrow_web/live/stop_live/stop_live.ex
lib/arrow_web/live/stop_live/stop_view_live.html.heex
lib/arrow_web/router.ex
test/arrow/stops_test.exs
test/arrow_web/controllers/stop_controller_test.exs
test/arrow_web/live/stop_live/stop_live_test.exs

**Asana Ticket:** [🏹 Import gtfs_creator shuttle stops into Arrow](https://app.asana.com/0/584764604969369/1207472819136798/f)
* Adds back a REST post endpoint for this work
* Adds Ecto validation to the stop form on phx-change
* Adds Ecto [unsafe_unique validation](https://hexdocs.pm/ecto/Ecto.Changeset.html#unsafe_validate_unique/4) to the stop form for stop_id (runs at changeset creation, unique constraint still runs on Repo.insert)
I considered whether we could write a SQL script to INSERT the stop records from gtfs_creator replacement bus into the arrow database but these changes seem worthwhile anyway.

feat: add http post for stops and use with liveview form

---

Dockerfile

Deploy to dev is failing on merge to main: https://github.com/mbta/arrow/actions/runs/10832864737/job/30058252111
```
> [elixir-builder  5/25] RUN echo "d72191eaa5d48fe2b6e044a0ae0b0e9f35e325b34b1ecab6ffe11d490d5cdb8f /root/aws-cert-bundle.pem" | sha256sum -c -:
0.253 /root/aws-cert-bundle.pem: FAILED
0.253 sha256sum: WARNING: 1 computed checksum did NOT match
```
```curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem | shasum -a 256```

chore: update aws cert bundle

---

lib/arrow_web/controllers/stop_controller.ex
lib/arrow_web/live/stop_live/stop_live.ex
lib/arrow_web/router.ex
test/arrow_web/live/stop_live/stop_live_test.exs

**Asana Ticket:** [🏹 Import shuttle stops](https://app.asana.com/0/584764604969369/1207472819136798/f)

feat: add update endpoint for stop_controller, use in stop_live

---

lib/arrow_web/controllers/api_html/stops_view.ex
test/arrow_web/controllers/api/stops_controller_test.exs

**Asana Ticket:** Relates to [importing shuttles](https://app.asana.com/0/584764604969369/1207472819136798/f)
Expose arrow id field so that we can use it to bulk update Arrow shuttle stops. In other situations, we can use `stop_id` under the stop's `attributes`

fix: expose arrow id for shuttle stops view

---

lib/arrow/shuttle/kml.ex
lib/arrow/shuttle/shape.ex
lib/arrow/shuttle/shape_kml.ex
lib/arrow/shuttle/shape_upload.ex
lib/arrow/shuttle/shapes_upload.ex
lib/arrow/shuttle/stop.ex
lib/arrow/shuttles.ex
lib/arrow/stops.ex
lib/arrow_web/controllers/shape_controller.ex
lib/arrow_web/controllers/shape_html.ex
lib/arrow_web/live/stop_live/stop_live.ex
test/arrow/shuttle/kml_test.exs
test/arrow/shuttle/shape_kml_test.exs
test/arrow/shuttle/shape_test.exs
test/arrow/shuttle/stop_test.exs
test/arrow/shuttle_test.exs
test/arrow/stops_test.exs
test/arrow_web/controllers/shape_controller_test.exs
test/support/factory.ex
test/support/fixtures/shuttles_fixtures.ex

**Asana Ticket:** No ticket, pre-work to shuttles implementation
Rename the Shuttle context to be Shuttles, this should have been pluralized originally. 
Phoenix documentation gives the example of "Catalog" and states:
> If you're stuck when trying to come up with a context name when the grouped functionality in your system isn't yet clear, you can simply use the plural form of the resource you're creating.

fix: fix naming of Arrow Shuttles context to plural Shuttles

---

lib/arrow_web/components/core_components.ex

I noticed the select input within the core components file was missing the "@errors" check that was added when the bootstrap styling was incorporated into `core_components`.

fix: fix error display of bootstrap styling for core_components select

---

lib/arrow/shuttles.ex
lib/arrow/shuttles/route.ex
lib/arrow/shuttles/route_stop.ex
lib/arrow/shuttles/shuttle.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/controllers/shuttle_controller.ex
lib/arrow_web/controllers/shuttle_html.ex
lib/arrow_web/controllers/shuttle_html/edit.html.heex
lib/arrow_web/controllers/shuttle_html/index.html.heex
lib/arrow_web/controllers/shuttle_html/new.html.heex
lib/arrow_web/controllers/shuttle_html/show.html.heex
lib/arrow_web/controllers/shuttle_html/shuttle_form.html.heex
priv/repo/migrations/20241018202407_add_fk_gtfs_route_shuttles.exs
priv/repo/seeds.exs
priv/repo/structure.sql
test/arrow/shuttles_test.exs
test/arrow_web/controllers/shuttle_controller_test.exs
test/support/fixtures/shuttles_fixtures.ex

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" Basic View + Route Definition Section](https://app.asana.com/0/584764604969369/1208185020019706/f)
The main bit to review in this PR is the shuttle form page on `/shuttles/new`, `/shuttles/1/edit`
You can populate your local database with example data for relations like Gtfs.Route, Shuttle.Shape with:
`mix run priv/repo/seeds.exs`
If you run into any issues with that, you may already have conflicting data in your local database; for fastest resolution, I'd recommend commenting out the conflicting parts of that script or completely resetting the data in your database via `mix db.reset` and re-running `mix run priv/repo/seeds.exs`

feat: add shuttle route definition to shuttles

---

lib/arrow_web/live/stop_live/stop_live.ex
lib/arrow_web/router.ex
test/arrow_web/live/stop_live/stop_live_test.exs

**Asana Ticket:** [🐛🏹 Fix Stop ID Validation in Stop Form](https://app.asana.com/0/1204137169527258/1208671244010889/f)

fix: edit stop broken after dependency update

---

config/dev.exs

**Asana Ticket:** no ticket, just a quick fix
I noticed that with #1028 you can use real Keycloak just fine, but because `ueberauth_provider: :keycloak` is now the default in `config.exs`, that's applied to dev as well and it will either use the real Keycloak flow if the environment variables are available, or just break otherwise. This changes it so that dev defaults to `:cognito`, causing it to still use the old fake Cognito login flow successfully, but if the environment variables are provided, `runtime.exs` will still overwrite it and use the real Keycloak service for authentication.

fix: use ueberauth_provider: :cognito on dev

---

lib/arrow/shuttles.ex
lib/arrow/shuttles/route.ex
lib/arrow/shuttles/route_stop.ex
lib/arrow/shuttles/shuttle.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow/shuttle/shuttle_test.exs
test/arrow/shuttles_test.exs
test/arrow_web/live/shuttle_live/shuttle_live_test.exs
test/support/factory.ex

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" - Stop Selection Section](https://app.asana.com/0/584764604969369/1208185020019710/f)
This should be the main PR implementing the functionality from the ticket. I think there are a couple of small subtleties I want to address related to the acceptance criteria (for instance, it sounds like we want to display a placeholder stop if there aren't any in a direction, but still allow saving in that case without persisting the placeholder), but I think this takes care of most of it.

Shuttle page stop section

---

lib/arrow/shuttles/route_stop.ex

**Asana Ticket:** followup on [🏹 Implement "Create/Edit Shuttle Route Definition" - Stop Selection Section](https://app.asana.com/0/584764604969369/1208185020019710/f)
@Whoops noticed that if you try adding multiple stops in a row without saving first, the stop IDs from the previously filled out (but non-persisted) stops get cleared out. I noticed when inspecting the changeset that the `add_stop` event was updating had a nil `display_stop_id` because previous events like `validate` that were generating and updating a changeset based on the form were correctly filling in the other stop-related fields but not casting `display_stop_id`. I added it to the array passed into `cast` and it seems to work now.

fix: don't clear stop ID when adding multiple stops

---

lib/arrow/shuttles.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
lib/arrow_web/live/shuttle_live/shuttle_view_live.html.heex
test/arrow/shuttles_test.exs

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" Map View + Route Shape Display](https://app.asana.com/0/1204473309455397/1208185020019708/f)

feat: display shape on map in shuttle definition pages

---

lib/arrow_web/live/shuttle_live/shuttle_live.ex

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" - Create Stop Function](https://app.asana.com/0/584764604969369/1208403724207314/f)
The [Miro mockups](https://miro.com/app/board/uXjVKVLTOI0=/?moveToWidget=3458764595370550770&cot=14) included a substantial amount of space between this line and the rest of the "define stops" section of the form.
I added a bit of top margin, but I figure that the look of the neighboring elements will change substantially in upcoming polish work and the correct margin can be set at that time.

feat: "Create Stop" link button

---

assets/package-lock.json
assets/package.json
assets/src/app.tsx
lib/arrow/shuttles/route_stop.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow/shuttle/route_stop_test.exs
test/arrow_web/live/shuttle_live/shuttle_live_test.exs
test/support/factory.ex

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" - Reorder Stops Function](https://app.asana.com/0/584764604969369/1208403724207316/f)
The first commit, 84204a4, just adds `typescript-language-server` as a dev-only dependency, which I do to keep it installed across different runs of `npm install` / `npm ci` with how my editor is set up. It should be harmless but I can remove it and work around it some other way if people don't want it in our dependencies.
As for the actual feature implementation, I had some issues getting LiveView hooks to play along nicely with TypeScript - I really wanted some kind of type that's something along the line of "thing that will be used to build a `ViewHook`" but I don't think that exists and I didn't see an easy way to build it using …

Drag and drop stops list

---

lib/arrow_web/controllers/auth_controller.ex
lib/arrow_web/controllers/layout_html/_header.html.heex
lib/arrow_web/controllers/layout_html/app.html.heex
lib/arrow_web/controllers/layout_html/live.html.heex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
lib/arrow_web/live/stop_live/stop_live.ex
lib/arrow_web/router.ex
test/arrow_web/controllers/auth_controller_test.exs

**Asana Ticket:** [🐛🏹 User attempting to log out receives internal server error](https://app.asana.com/0/584764604969369/1208162530217806/f)
When logging out through Keycloak, the logout URL was not including the auth provider in the URL. This trips up `Ueberauth` and causes it to load the request through the `request/2` endpoint instead of the intended `logout/2` endpoint. The logout URL can be the same (`~p"/auth/keycloak/logout"`) throughout the app so I removed the `@logout_url` param and hardcoded it into the logout button in the header.

fix: Keycloak Logout

---

lib/arrow/shuttles.ex
lib/arrow/shuttles/route_stop.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow/shuttles_test.exs

**Asana Ticket:** [Follow up on "🏹 Implement "Create/Edit Shuttle Route Definition" - Time to Next Stop"](https://app.asana.com/0/584764604969369/1209003091082862/f)
* Add fetching of stop data (lat/long) when the initial shuttle hasn't been created yet
* Add explicit error handling for when there is only one stop defined for a direction
Part of this is similar to what the Map component does (Ecto.assoc_loaded? & calling `preload`) but if those values aren't set yet, then this uses a virtual field `display_stop` mirroring `display_stop_id`. This isn't the most elegant solution, opening this as a draft for now.

fix: add handling for retrieve estimates on new shuttle creation

---

lib/arrow/shuttles.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/components/stop_input.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow/shuttles_test.exs
test/arrow_web/live/shuttle_live/shuttle_live_test.exs

**Asana Ticket:** [🏹 Implement "Create/Edit Shuttle Route Definition" - Enhanced Stop Search](https://app.asana.com/0/584764604969369/1208355675343698/f)
I'm still hoping to get some unit testing of the component behavior itself working, but running into issues - see [discussion on Slack](https://mbta.slack.com/archives/C07639BHFKR/p1734364042594779). However, everything else should be in place for reviewing.

Stop ID autocomplete

---

Dockerfile

**Asana Ticket:** N/A
Our checksum is outdated and is blocking deployments. Updated it and merged both `RUN` commands into a single `ADD --checksum` command.

fix: Update AWS Checksum

---

lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow_web/live/shuttle_live/shuttle_live_test.exs

* Uses inputs_for for the route_stops section on the initial form (nested)
* Removes combine_params (no longer needed)
* Uses flex ordering to visually order the form inputs by route definition then by route_stops

refactor(shuttles): use nested form for route_stops

---

lib/arrow/shuttles.ex
lib/arrow/shuttles/shuttle.ex
lib/arrow/util.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/components/shuttle_input.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.html.heex
test/arrow/util_test.exs
test/arrow_web/live/disruption_v2_live_test.exs

**Asana Ticket:** [🏹 Implement "Create New Replacement Service Component" basic view](https://app.asana.com/0/584764604969369/1208885496650094/f)
This allows a user to click and start entering a replacement shuttle, including selecting the name of the shuttle from a dropdown of available shuttles, with auto-complete. Validation and save are explicitly out of scope and will go in a followup ticket / PR.

New replacement service component

---

lib/arrow/shuttles/shuttle.ex
test/arrow/shuttle/shuttle_test.exs
test/arrow_web/controllers/api/shuttle_controller_test.exs

**Asana Ticket:** [[extra] 🏹🐛 Shuttles can be saved as active without time to next stop](https://app.asana.com/0/584764604969369/1209094056922520/f)
I wonder if it would also make sense to add validation that the final stop in each direction does _not_ have a `time_to_next_stop`, since it isn't meaningful. That might be a bit over-zealous, though.

fix: validate time_to_next stop for activating shuttle

---

lib/arrow/shuttles/route_stop.ex
test/arrow/shuttle/route_stop_test.exs

**Asana Ticket:** No ticket, came out of investigation from another ticket
Adds invalid stop_id value to the Changeset error (see [add_error docs](https://hexdocs.pm/ecto/Ecto.Changeset.html#add_error/4-examples))

feat: add data to RouteStop changeset error for an invalid stop ID

---

lib/arrow_web/components/stop_input.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow_web/live/shuttle_live/shuttle_live_test.exs

**Asana Ticket:** [[extra] 🏹🐛 Map view - stops index changing (from first stop as 0 or as 1](https://app.asana.com/0/584764604969369/1209034382499890/f)
Problem:
When re-ordering shuttle stops for a new shuttle, the indexing of stops would change from 1-based to 0-based after the first reordering. 
Solution:
Start using 1-based indexing for stops in the `stop_input` component. 
Problem:
When re-ordering shuttle stops for a new shuttle, stops with auto-completed names would switch from the auto completed value (e.g.  1 - Washington St opp Ruggles St) to just the value of the stop ID e.g. just 1
Solution:
On every re-render of stops, ensure that the value of the `stop_input` component is the human readable value. I fetch from the stop from the changeset if it's already there, otherwise I …

fix(shuttles): Fix indexes changing to 0-based and displayed stop names changing when stops are reordered

---

lib/arrow/shuttles/definition_upload.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
test/arrow_web/live/shuttle_live/shuttle_live_test.exs

**Asana Ticket:** [[extra] 🏹🐛 [edit only] Upload Shuttle Definition XLSX then Retrieve Estimates - retrieve estimate does nothing (websocket crash)](https://app.asana.com/0/584764604969369/1209034382499892/f)
* This patches the issue when the uploaded XLS doesn't produce a valid route_stops changeset
* We now error on upload if the changeset would be invalid (in the current case, if the stop doesn't exist), instead of allowing the invalid casted changeset to be applied to the form

fix(shuttles): call Changeset.apply_action after uploading xlsx

---

lib/arrow/shuttles/route.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
priv/repo/migrations/20250121165457_drop_shuttles_invalid_direction_descriptions.exs
priv/repo/seeds.exs
priv/repo/structure.sql
test/arrow_web/live/shuttle_live/shuttle_live_test.exs
test/support/fixtures/shuttles_fixtures.ex

**Asana Ticket:** [[extra] 🏹 Change direction_desc to drop-down (in Shuttle Definitions)](https://app.asana.com/0/584764604969369/1209163082064165/f)
Problem:
Direction description on the shuttle form was a free text field, but in reality there are a fixed number of potential descriptions [for a direction.](https://github.com/mbta/gtfs-documentation/blob/master/reference/gtfs.md#directionstxt)
Solution:
Make direction description a drop-down menu instead of a free-text box.

feat(shuttles): Make the direction description a drop-down menu instead of free text

---

lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex
lib/arrow_web/router.ex

After saving a disruption, you remain at `/new` which means you can't edit a disruption after immediately after creating it. If we move these routes into a `live_session`, we can navigate the user without reloading the page.

tweak: Show edit page after saving disruption

---

assets/css/bootstrap.css
lib/arrow_web/components/limit_section.ex
lib/arrow_web/components/replacement_service_section.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex

**Asana Ticket:** Follow on to [🏹 Implement "Create Replacement Service Component" - Shuttle Activation Upload/Parsing + Save Component Button](https://app.asana.com/0/584764604969369/1208991517812079/f)
* This updates the styling of the form itself (not the list view)

feat: polish to replacement_service form

---

.github/workflows/ci.yml

**Asana Ticket:** [[extra] Fix arrow CI due to deprecation in Github actions/cache](https://app.asana.com/0/584764604969369/1209332349518242)

ci: upgrade actions/cache from v2 (deprecated) to v4

---

lib/arrow_web/components/limit_section.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex
test/arrow_web/live/disruption_v2_live_test.exs

**Asana Ticket:** [🏹🐛 Disruption limit component create form doesn't close after save](https://app.asana.com/0/584764604969369/1209292019824563/f)
Problem:
The limit form was not closing after a new limit was created.
Solution:
Set the correct value (`@limit_in_form`) to `nil` such that the limit form is no longer displayed after a new disruption limit gets created. Add unit test covering this case

fix(disruptionsv2): disruption limit form is closed after limit is created

---

lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex

**Asana Ticket:** [[extra] 🏹🐛 Disruption replacement service component create form doesn't close after save](https://app.asana.com/0/1205718273834959/1209333426359266)
Same fix as [🏹🐛 Disruption limit component create form doesn't close after save](https://app.asana.com/0/584764604969369/1209292019824563) given the pattern duplication

fix: don't open a new replacement_service form after create or update

---

lib/arrow_web/components/replacement_service_section.ex

**Asana Ticket:** [🐛🏹 Disruptions: map sits on top of shuttle selection dropdown](https://app.asana.com/0/1205718273834959/1209309553641279)
The dropdown already sets a z-index of 50. Set the sibling map row to have a lower z-index.

fix(disruptionsv2): allow shuttle select dropdown on top of map

---

lib/arrow/disruptions/disruption_v2.ex
lib/arrow/disruptions/limit.ex
lib/arrow/limits/limit_day_of_week.ex
lib/arrow_web/controllers/disruption_v2_controller.ex
lib/arrow_web/controllers/disruption_v2_controller/filters.ex
lib/arrow_web/controllers/disruption_v2_controller/filters/calendar.ex
lib/arrow_web/controllers/disruption_v2_controller/filters/helpers.ex
lib/arrow_web/controllers/disruption_v2_controller/filters/table.ex
lib/arrow_web/controllers/disruption_v2_html.ex
lib/arrow_web/controllers/disruption_v2_html/calendar.ex
lib/arrow_web/controllers/disruption_v2_html/index.html.heex
test/arrow_web/views/disruption_v2_view/calendar_test.exs

**Asana Ticket:** [🏹 Implement Arrow v2 calendar view](https://app.asana.com/0/584764604969369/1209170968037057)
Added the calendar view for v2 Arrow disruptions. The framework of the view was copied from v1. Had to massage the data a bit to make it work for limits/replace services. Decided to keep the `DisruptionCalendar` component piece of it because it was easier than building a new calendar from scratch.

feat: v2 Calendar View

---

lib/arrow_web/components/replacement_service_section.ex
lib/arrow_web/components/shuttle_input.ex
test/arrow_web/live/disruption_v2_live_test.exs

**Asana Ticket:** [🐛🏹 Shuttle input reverts to shuttle_id](https://app.asana.com/0/1205718273834959/1209370632856918)
This input is used in a form where it passes the value via `form[:shuttle_id]`
This fixes a bug where we display the form field value of `:shuttle_id` if the input value is reset
Reproduced on dev after selecting a new input value

fix(disruptionsv2): add value_mapper for shuttle_input

---

lib/arrow/disruptions.ex
lib/arrow_web/controllers/disruption_v2_controller.ex
lib/arrow_web/controllers/disruption_v2_controller/filters.ex
lib/arrow_web/controllers/disruption_v2_controller/index.ex
lib/arrow_web/controllers/disruption_v2_html.ex
lib/arrow_web/controllers/disruption_v2_html/_table.html.heex
lib/arrow_web/controllers/disruption_v2_html/index.html.heex
test/arrow_web/controllers/disruption_v2_controller/filters_test.exs
test/arrow_web/controllers/disruption_v2_controller_test.exs
test/integration/disruptions_v2_test.exs

**Asana Ticket:** [🏹 Implement route selection + button filters](https://app.asana.com/0/584764604969369/1209170968037051)

Disruption list route filter

---

lib/arrow/shuttles/shuttle.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/components/replacement_service_section.ex
lib/arrow_web/components/shuttle_input.ex
test/arrow/shuttle/shuttle_test.exs

**Asana Ticket:** [🏹🐛 [extra] Arrow allows draft shuttles to be selected as replacement service](https://app.asana.com/0/584764604969369/1209486270766204)
Unfortunately I still don't see a great way of testing the LiveSelect behavior in unit tests, but I am open to suggestions and I have performed manual testing.

Don't allow draft shuttles as replacement service

---

lib/arrow/disruptions/replacement_service.ex
lib/arrow_web/controllers/api/shuttle_controller.ex
lib/arrow_web/controllers/api_html/shuttle_route_view.ex
lib/arrow_web/router.ex
test/arrow_web/controllers/api/replacement_service_controller_test.exs
test/arrow_web/controllers/api/shuttle_controller_test.exs

While working on the GTFS work for replacement services, I realized I didn't have access to route shapes for shuttles. Added an attribute to the API response to expose this. `gtfs_creator` turns kml file names into shape_ids so I did some formatting of the shape `path` with that in mind.
A couple of other tweaks in here:
1. Added back an auth plug that I think was unintentionally removed.
2. Reduced some nesting in the replacement service API response.

tweak: Expose Shuttle shapes in API response

---

config/prod.exs
config/runtime.exs
lib/arrow_web/endpoint.ex

Something about socket connections in dev causes LiveView forms to break every once in a while. After some discussion in Slack, we aren't exactly configuring our `Endpoint` in the [recommended way](https://github.com/phoenixframework/phoenix/blob/487618b272d694388c323a676c2335cf7fa972e0/lib/phoenix/socket/transport.ex#L367).  Instead of setting `check_origin`, we should set `[url: [host: ...]]` correctly. I added `HOST` to the ENV of all Arrow environments. 
This branch is currently on dev and forms are working fine.

chore: Use recommended Endpoint config

---

config/config.exs
config/dev.exs
config/prod.exs
config/runtime.exs
config/test.exs
lib/arrow/disruptions/disruption_v2.ex
lib/arrow/hastus.ex
lib/arrow/hastus/export.ex
lib/arrow/hastus/export_upload.ex
lib/arrow/hastus/service.ex
lib/arrow/hastus/service_date.ex
lib/arrow_web/components/hastus_export_section.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex
priv/repo/migrations/20250312170355_create_hastus_export_tables.exs
priv/repo/structure.sql
test/arrow/hastus/export_upload_test.exs
test/arrow/hastus_test.exs
test/integration/disruptionsv2/hastus_export_section_test.exs
test/support/fixtures/hastus_fixtures.ex

**Asana Ticket:** [🏹 Implement HASTUS import forms (post-parse)](https://app.asana.com/1/15492006741476/project/584764604969369/task/1209538099020504)
This PRs finishes the form submission that saves HASTUS exports to the DB and S3. Follows the same S3 uploading pattern as Shapes. There is not currently a way to view existing exports so easiest way to test is locally. After saving, `hastus_exports`, `hastus_services`, and `hastus_service_dates` rows should be created and S3 should contain the uploaded file.

feat: HASTUS export form submission

---

lib/arrow/disruptions.ex
lib/arrow/disruptions/replacement_service.ex
lib/arrow_web/controllers/timetable_controller.ex
test/arrow/disruptions_test.exs
test/arrow_web/controllers/timetable_controller_test.exs

**Asana Ticket:** [[extra] 🏹🐛 Fix replacement service timetable view](https://app.asana.com/0/584764604969369/1209732403584287/f)
While testing Arrow <-> gtfs-creator integration, we found a timetable view crash. While investigating, we realized that the `/api/replacement-service` endpoint was not showing the same issue. This is because it was using different logic for building the timetables. Seemed like a good opportunity to DRY the code up a bit and fix a bug at the same time.

refactor: Timetable logic

---

lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex
test/arrow_web/live/disruption_v2_live_test.exs

**Asana Ticket:** [🏹 Set base disruption status and mode values when creating a disruption](https://app.asana.com/0/1206766411887385/1209773527666857/f)
Disruptions are not allowed to be active unless they already exist. `Pending` will now be the default and only option under "Approval Status" for new disruptions.
Arrow v2 MVP will only allow subway disruptions. Other options are disabled until implemented.

polish: Set default radio button values

---

README.md

Running `direnv allow` needs to happen _after_ copying `.envrc.example` to `.envrc` and updating that file with all of the relevant secrets.

docs: correct order of setup steps

---

assets/package-lock.json

Running `npm install` produced these changes likely because these are from mix dependencies that have been updated since the last time we touched `assets/package.json`.

deps: update mix installed npm deps in package-lock.json

---

lib/arrow/hastus/service.ex
lib/arrow_web/components/hastus_export_section.ex

A couple of quick fixes for the HASTUS section.
1. Change default value of `import?` for new exports
2. Fix bug where edit/delete buttons were hidden if an export has a service with `import? == false`.

HASTUS import polish

---

lib/arrow/hastus/service.ex

`Arrow.Hastus.Service` defined a relationship (`.export`) to `Arrow.Hastus.Service` when it should be to `Arrow.Hastus.Export`

fix: hastus service -> export association

---

lib/arrow/shuttles/shuttle.ex
test/arrow/shuttle/shuttle_test.exs

**Asana Ticket:** [[extra] 🏹🐛 Shuttle Definitions page doesn't register existing "time to next stop" values when shuttle status is changed from inactive -> active](https://app.asana.com/0/584764604969369/1209773527666853/f)
The root cause of this bug is that replacing the route stops actually results in two changesets, a `:replace` changeset for the old route stop being removed and an `:insert` changeset for the new one. The validation was just looking at all changesets, so it was seeing two with a time to next stop of nil rather than the expected one. This just updates the logic to filter out `:replace` and `:delete` changesets and also make sure that the list is sorted by stop sequence before validating.

fix: check changesets correctly when verifying for time to next stop

---

Dockerfile

**Asana Ticket:** no ticket
It looks like the certificate bundle has changed, so I have updated the hash, confirming that the hash matches what I get when I download the file locally.

chore: update AWS cert bundle hash

---

lib/arrow/disruptions/limit.ex
priv/repo/migrations/20250402181804_add_limit_exclusion_constraint.exs
priv/repo/structure.sql
test/arrow_web/controllers/api/limit_controller_test.exs

Adds an [exclusion constraint] to the limits table that prevents inserting limits that are part of the same disruption, route, have the same boundary stops (regardless of order), and an overlapping date range.
Errors for this exclusion constraint are shown on the `end_date` field per a [Slack discussion with Firas][slack discussion].
[🏹🐛 Disallow users from creating limits with overlapping dates][asana]
[exclusion constraint]: https://postgresql.org/docs/17/interactive/sql-createtable.html#SQL-CREATETABLE-EXCLUDE
[asana]: https://app.asana.com/0/584764604969369/1209829602417088/f
[slack discussion]: https://mbta.slack.com/archives/C06R4UC5A0Y/p1743535027110439?thread_ts=1743529901.408249&cid=C06R4UC5A0Y

fix: prevent creating limits with overlapping dates

---

lib/arrow/disruptions/limit.ex
lib/arrow_web/components/limit_section.ex
test/support/fixtures/limits_fixtures.ex

Adds a validation to the limit changeset to ensure at least one of the limit day of weeks is active. Also handles showing this in the UI either on submission or if the inputs of the day of weeks have changed.
[🏹🐛 Users can save a limit with no days selected](https://app.asana.com/0/584764604969369/1209887002402269/f)

fix: prevent saving limit without weekday/time-of-day completed

---

lib/arrow/shuttles/shuttle.ex
test/arrow/shuttle/shuttle_test.exs

**Asana Ticket:** [[extra] 🏹🐛 Some shuttle definitions are marked as active without required fields](https://app.asana.com/0/584764604969369/1209881923550837/f)
Problem:
You can make a shuttle active without the shuttle having a shape for its route.
Solution:
Prevent users from setting a shuttle to active if its route doesn't have a valid shape

fix(shuttle): reject shuttles without a route shape

---

lib/arrow/disruptions.ex
lib/arrow/hastus.ex
lib/arrow/hastus/export_upload.ex
lib/arrow/hastus/service.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/components/hastus_export_section.ex
lib/arrow_web/components/limit_section.ex
priv/repo/migrations/20250403191728_add_start_and_end_stop_ids_to_hastus_services.exs
priv/repo/structure.sql
test/arrow/hastus/export_upload_test.exs
test/arrow/hastus_test.exs
test/integration/disruptionsv2/hastus_export_section_test.exs

- Adds start_stop_id and end_stop_id to hastus services
- Updates export upload to derive limits from hastus exports
- This looks at the stop_sequences for the trips within the services in the export to determine the boundary stops
- Renders hastus services with limits in the UI
[🏹 Implement HASTUS export-derived limits determination & display](https://app.asana.com/0/584764604969369/1209459244072060/f)
**Note**: This skips an integration test that I could not for the life of me figure out a way to fix. It is unclear to me what exactly wasn't working. The screenshots from the test either showed exactly what the error said was missing or a progress bar. Some sort of race condition?

feat: derive limits from hastus exports

---

.github/workflows/ci.yml
assets/css/base.css
assets/css/navbar.css
lib/arrow_web/components/core_components.ex
lib/arrow_web/controllers/disruption_html/index.html.heex
lib/arrow_web/controllers/shape_html/index.html.heex
lib/arrow_web/controllers/shuttle_html/index.html.heex
lib/arrow_web/controllers/stop_html/index.html.heex
priv/repo/structure.sql
test/arrow_web/components/core_components_test.exs
test/integration/disruptions_test.exs

**Asana Ticket:** [[extra] 🏹💅🏻🇵🇱  Prevent header jitter](https://app.asana.com/0/584764604969369/1209389762315006/f)
Problem:
The navbar tends to "jitter" (more precisely, there is layout shift) when switching pages on the new DisruptionsV2 home view. See the video attached in the Asana ticket I've linked.
Solution:
Set navbar buttons to a fixed width so that their size doesn't change whenever the text within them is rendered. Also revised some stylistic issues with buttons on other pages, and fixed a bug that was breaking sorting for the stops page.

fix(navbar): resolve header jitter

---

.github/workflows/ci.yml

Uses actions/upload-artifact to make the screenshots captured by wallaby for failed integration tests available for download

ci: save wallaby screenshots after integration test failures

---

lib/arrow_web/components/hastus_export_section.ex
lib/arrow_web/components/limit_section.ex
lib/arrow_web/components/replacement_service_section.ex
lib/arrow_web/live/disruption_v2_live/disruption_v2_view_live.ex

- moves the delete icon to the bottom right corner of the replacement service section
- add vertical padding around each section on the disruptions v2 page
- update copy in service schedules section
[🏹💅🏻🇵🇱 Create/Edit disruption Pages UI polish](https://app.asana.com/1/15492006741476/project/584764604969369/task/1209777154957386?focus=true)

chore: create/edit disruption pages ui polish

---

lib/arrow/shuttles/shape.ex
lib/arrow_web/controllers/shape_controller.ex
lib/arrow_web/controllers/shape_html/select.html.heex
priv/repo/structure.sql
test/arrow/shuttles_test.exs
test/arrow_web/controllers/shape_controller_test.exs
test/support/fixtures/shuttles_fixtures.ex

- Adds new fields for "From", "To" and "Via" which are then combined to create the shape `name`
- Validates PascalCase for the generated names
- Removes the dump inspected coords from success flash message
[Asana](https://app.asana.com/1/15492006741476/project/584764604969369/task/1209989320086485?focus=true)

chore: update save shape page/form

---

lib/arrow_web/controllers/api/disruption_controller.ex
lib/arrow_web/router.ex
test/arrow_web/controllers/api/disruption_controller_test.exs

In the current v1 Arrow disruptions endpoint, we return every disruptions whether it is active or not. This creates a lot of extra work for gtfs_creator because it applies all of these disruptions even though they will be truncated out for being outside the current rating. Adding this endpoint for gtfs_creator to use in an upcoming PR.

v1 Arrow API endpoint for active disruptions

---

lib/arrow/shuttles/route.ex
lib/arrow/shuttles/shuttle.ex
lib/arrow_web/controllers/api_json/shuttle_route_view.ex
lib/arrow_web/controllers/api_json/shuttle_view.ex
lib/arrow_web/live/shuttle_live/shuttle_live.ex
priv/repo/migrations/20250501125059_move_shuttle_suffix_column.exs
priv/repo/structure.sql
test/arrow_web/live/shuttle_live/shuttle_live_test.exs
test/support/fixtures/shuttles_fixtures.ex

We are adding Local and Express shuttles to Arrow for the first time and found that suffixes aren't being applied to the shuttle routes correctly. This lead me to realize that this field is associated with the wrong model. There should be a single `Suffix` input for each shuttle instead of one for each shuttle direction.

Move suffix from shuttle_routes to shuttles.

---

lib/arrow_web/controllers/api/notice_controller.ex

This failure didn't pop up until running the prod deploy. Now that there is a good chance we won't process any v1 disruptions, we should handle an empty list of `revision_ids`.

Don't fail if not given any revision_ids.

---

lib/arrow/shuttles.ex
lib/arrow_web/controllers/shape_controller.ex

Shape deletion would sometimes leave things in a broken state. If a shape was used by a shuttle the delete operation would first delete the saved shape file and then fail to delete the database record because of the foreign key constraint on `shuttle_routes`. This change refactors that code to prevent this broken state and provide better feedback to the user.
- Reorders the database and saved shape file deletion so that the database delete happens _before_ the saved shape file delete. This ensures that if a database operation fails the saved shape file isn't deleted (this is what was causing the 500 errors).
- Wraps the delete in the database and the delete of the saved shape in a database transaction to ensure that a failure to delete the remote shape does not delete the database record …

fix: error when attempting to delete shapes that are used by shuttles

---

assets/package-lock.json
assets/src/components/ShapeViewMap.tsx
lib/arrow/shuttles.ex
lib/arrow_web/controllers/shape_controller.ex
lib/arrow_web/controllers/shape_html.ex
test/arrow/shuttles_test.exs

Updates some codepaths to prevent 500 errors on pages that reference a broken shape.
Viewing a broken shape will flag that the shape is broken. Viewing a shuttle that references a broken shape will simply not have any shapes to render (the failure is silent).
[Asana task](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210046524302364?focus=true)

fix: handle errors when a shape file is missing

---

assets/src/app.tsx

`oldDraggableIndex` and `newDraggableIndex` appear to be one-indexed instead of zero-indexed. This causes an `Enum.at/2` call in `shuttle_live.ex` to return `nil` instead of the moved stop struct. Subtracting one from each allows the reordering to work as expected.

Fix: Shuttle Stop Reordering

---

assets/src/app.tsx
lib/arrow/hastus/export_upload.ex
lib/arrow_web/components/core_components.ex
lib/arrow_web/components/edit_hastus_export_form.ex

Updates the edit hastus export form to special case when a hastus export has trips with invalid or missing shapes.
Also adds a new `send_download` function in `CoreComponents` which uses a new client-side event handler to send data over the existing LiveSocket connection and trigger a client-side download of that data. This makes sending one-off files from a LiveView much easier than the alternative of creating a separate controller to send the file.
[Asana task](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210125477521799?focus=true)

feat: add download of list of trips/services with missing shapes

---

lib/arrow_web/components/edit_disruption_form.ex

**Asana Ticket:** [🏹🐛 [Edit Disruption] Editing disruption fundamentals changes approval status](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210251521149558?focus=true)
I think this is left over from pre-refactor. We only want to hardcode the value of `is_active` for new disruptions. On this edit page, just use the value the disruption already has.

fix: Don't change is_active on page load.

---

lib/arrow/disruptions/limit.ex
lib/arrow/limits/limit_day_of_week.ex
lib/arrow_web/components/edit_limit_form.ex
test/arrow/disruptions/limit_test.exs
test/integration/disruptions_v2_test.exs
test/support/factory.ex
test/support/fixtures/limits_fixtures.ex

**Asana Ticket:** [🏹💅🏻🇵🇱 [Limit Create/Edit] Warn on user selecting out-of-range dates/days-of-week](🏹💅🏻🇵🇱 [Limit Create/Edit] Warn on user selecting out-of-range dates/days-of-week)
User is now prevented from saving a limit if it has an active day outside of its specified date range.
<details>
<summary>Demo of the validation in create workflow</summary>
https://github.com/user-attachments/assets/a377038d-6c7d-4648-b5db-85ef52b15fcc
</details>
<details>
<summary>Demo of the validation in edit workflow</summary>
https://github.com/user-attachments/assets/b1ffbcf0-f800-45b2-a2e7-16cbb923518d
</details>
---
**I did a slightly non-standard thing for this:**
I wanted the error message to appear under the offending day-of-week row(s), but the error applies to the entire day-of-week and not a …

feat(limits): Warn on days-of-week outside of the specified date range

---

lib/arrow_web/components/disruption_components.ex

**Asana Ticket:** [🏹💅🏻🇵🇱 [Create/Edit Disruption] Fix wrapping + fonts in disruption fundamentals ](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210329320359079?focus=true)
The original intent of the `pre` tags was to preserve new lines. If we use `white-space: pre-wrap` instead, we still preserve new lines while also wrapping long text and maintaining a consistent font.

fix: Adjust font and text wrapping of disruption description.

---

lib/arrow_web/controllers/api/shapes_controller.ex
lib/arrow_web/controllers/api_json/shapes_view.ex
lib/arrow_web/router.ex
test/arrow_web/controllers/api/shapes_controller_test.exs

**Asana Ticket:** [🏹 Regular sync of Arrow Stops & Shapes from prod to dev](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210252044451003?focus=true)
PR 1 of 2 for this feature. Arrow doesn't currently have an API endpoint for fetching all shapes, and Arrow dev won't have access to Arrow-prods' S3 bucket. This adds an endpoint for listing all shapes, including presigned URLs that dev will be able to use in order to obtain said shape(s).

feat: add API endpoint for accessing shapes

---

lib/arrow/hastus/service.ex

**Asana Ticket:** -
Fixes presentation of derived limit end dates. Oops!

fix: Use service_date.end_date in Service.last_date/1

---

lib/arrow/hastus/export_upload.ex
lib/arrow_web/components/edit_hastus_export_form.ex
test/arrow/hastus/export_upload_test.exs

**Asana Ticket:** [[extra] 🏹 Rename HASTUS exports being uploaded in case of duplicates](https://app.asana.com/1/15492006741476/project/1204473309455397/task/1210920379529810?focus=true)

fix: ensure unique name when uploading hastus exports

---

lib/arrow/disruptions/replacement_service.ex

Context: [#1297 (comment)](https://github.com/mbta/arrow/pull/1297#discussion_r2301036851)
Follows-onto: #1297
I really liked [@jzimbel-mbta's suggestion](https://github.com/mbta/arrow/pull/1297#discussion_r2301036851) but ran into some test failures in the `ArrowWeb.TimetableControllerTest` "simply" implementing it.
I found that this was due to how the `day_of_week` is determined when it is not specified in the query parameters. Because map key ordering is not specified in Elixir, this ended up _also_ changing the order of the tabs on the timetable view.
So this PR sorts the available days on the Controller.

feedback:refactor: derive `schedule_service_types` from `@service_type_to_workbook_abbreviation`
